#!/bin/sh
dir=`dirname "$0"`
source="$1"
target="$2"
shift
shift
prefix=/opt/webenabled/data
run()
{
  echo "  Running $@"
  "$@"
}

error()
{
  echo "ERROR${1+: }$@" >&2
  exit 1
}

usage()
{
  echo "Usage: clone-vhost SOURCE_VHOST TARGET_VHOST" >&2
  exit 1
}

$dir/check-vhost-name archive "$source" || usage
$dir/check-vhost-name restore "$target" || usage

TMPDIR=`$dir/archive-mktemp` || exit 1

echo "Cloning stage 1: archive $source to $TMPDIR"
if ! $dir/archive-vhost "$source" "$TMPDIR"
then
  echo ERROR >&2
  exit 1
fi
  
echo "Cloning stage 2: restore $target from $TMPDIR"
$dir/restore-vhost "$target" "$TMPDIR" "$@" || error
echo "Cloning stage 3: removing archive from $TMPDIR"
rm -rf "$TMPDIR" || error
echo Done
