#!/bin/bash

set_usage_msg "$namespace" \
  "Usage: $bin_name $action $object [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost to protect

  Disables htpasswd protection on the specified vhost.
"

app_disable_htpasswd() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost file

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        vhost="$2"
        shift 2
        ;;
      *)
        error "unknown option $name"
        ;;
    esac
  done

  if [ -z "$vhost" ]; then
    error "missing --vhost option"
  fi

  echo "htaccess-unlock-vhost $vhost"
}
