#!/bin/bash
#
# chkconfig: 2345 51 49
# description: starts devPanel basic services
# processname: devpanel-bootstrap

### BEGIN INIT INFO
# Provides: devpanel-bootstrap
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts devPanel basic services
# Description: starts devPanel basic services
### END INIT INFO


usage() {
  echo "Usage: $0 <start|stop|status>"
  exit 1
}

[ -z "$1" ] && usage

declare -l action="$1"

case "$action" in
  start)
    devpanel bootstrap --yes
    ;;

  stop)
    echo "OK (though nothing actually executed)"
    ;;

  reload|restart)
    devpanel bootstrap --yes
    ;;

  status)
    echo "OK (though nothing actually executed)"
    ;;
esac
