#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action $object [opts] --vhost <vhost> --name-value name=value

  Options:
    --vhost <vhost>             the vhost
    --name-value <name=value>   sets the specified name and value

  Sets specific name and value pairs to the specified application.
"

devpanel_cmd__app_config() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost admin_pw

  local -a cmd_args=()
  local -a opts_ar=( )

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --admin-password)
        [ -z "$2" ] && error_missing_value admin-password
        admin_pw="$2"
        shift 2
        ;;
      --name-value)
        [ -z "$2" ] && error_missing_value name-value
        if [[ "$2" == *=* ]]; then
          opts_ar+=( -O "$2" )
        else
          error "invalid value passed to option --name-value"
        fi

        shift 2
        ;;
      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $name"
        ;;
      *)
        cmd_args+=( "$name" )
        shift
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  if [ ${#opts_ar[*]} -eq 0 -a -z "$admin_pw" ]; then
    usage
  fi

  user="w_${vhost}"

  local exec_bin="$sys_dir/bin/restore-vhost-subsystem"

  if [ -n "$admin_pw" ]; then
    echo "$admin_pw" | su -l -c "$exec_bin -i -p" "$user"
  fi

  if [ ${#opts_ar[*]} -gt 0 ]; then
    su -l -c "$exec_bin"\ "${cmd_args[*]}"\ "${opts_ar[*]}" "$user"
  fi
}
