#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action $object [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost to protect

  Enables Let's Encrypt certificates on the specified vhost.
"

devpanel_cmd__lets_encrypt_enable() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost file
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      *)
        cmd_args+=( "$name" )
        shift
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  "$sys_dir/libexec/lets-encrypt-wrapper" enable $vhost
}
