#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action $object [opts] --domain <domain> 

  Options:
    --domain <domain>         the domain name you're looking for (e.g.
                              whatever.com)

  Searches the specified domain in the local server and returns the vhost
  associated with it.
"

devpanel_cmd__domain_find() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost domain
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --domain)
        [ -z "$2" ] && error_missing_value domain
        domain="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      *)
        error "unknown option $name"
        ;;
    esac
  done

  [ -z "$domain" ] && error_missing_param domain

  . $sys_dir/lib/functions

  vhost=$(get_vhost_with_hostname "$domain")
  if [ $? -eq 0 ]; then
    local app=$(get_app_type_from_vhost "$vhost")
    [ -z "$app" ] && app=unknown

    printf "  vhost: %-10s app: %-10s domain: %s\n" \
      "$vhost," "$app," "$domain"
  else
    echo "Domain not found on this server"
    return 1
  fi
}
