#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action $object [opts] --vhost <vhost>

  Lists the vhosts on this server.
"

vhosts_list() {
  local vhost vhosts_ar name app default_host url

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --help)
        usage
        ;;
      *)
        usage
        ;;
    esac
  done

  . $sys_dir/lib/functions

  vhosts_ar=( $(get_list_of_vhosts) )

  if [ ${#vhosts_ar[@]} -eq 0 ]; then
    echo "No vhost on this server."
    return 0
  fi

  echo "Virtual hosts:"
  echo

  for vhost in ${vhosts_ar[@]}; do
    default_host=$(get_vhost_key_value "apache_vhost:0:_:ServerName" \
                                        $vhost 2>/dev/null)

    app=$(get_vhost_key_value app:0:_:seed_app $vhost 2>/dev/null)
    url="http://$default_host/"
    printf "  vhost: %-6s app: %-10s url: %s\n" "$vhost" "$app" "$url"
  done

  echo
}
