#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action $object [opts] --vhost <vhost>

  Options:
    --vhost     <vhost>         the vhost to protect
    --add-user  <username>      add the specified user
    --del-user  <username>      delete the specified user
    --chpasswd  <username>      changes the password of the specified user

  Of the options to add, remove and change password, only one can be used at
  a time.

  Manage htpasswd users.
"

devpanel_cmd__htpasswd_manage() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost file password
  local op op_str
  local -a cmd_args=()

  local -i exclusive_ops=0

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --add-user|--del-user|--chpasswd)
        [ -z "$2" ] && error_missing_value ${name#--}
        exclusive_ops+=1
        username="$2"
        op=${name#--}
        shift 2
        ;;

      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $name"
        ;;
      *)
        cmd_args+=( "$name" )
        shift
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  if [ $exclusive_ops -gt 1 ]; then
    error "only one of --add-user, --del-user, --chpasswd can be used a time"
  fi

  if [ -z "$op" ]; then
    local errmsg
    errmsg="no option choosen. "
    errmsg="One of --add-user, --del-user or --chpasswd needs to be specified"
    error "$errmsg"
  fi

  [ -z "$username" ] && error_missing_param username

  local has_tty

  if tty -s; then
    has_tty=1
  fi

  if [ "$op" == "add-user" -o "$op" == "chpasswd" ]; then
    while [ -z "$password" ]; do
      read ${has_tty:+-s} -p "Password: " password
    done
    echo # for the next line to start after the Password:
  fi

  case $op in
    add-user)
      op_str="+:$username:$password"
      ;;
    del-user)
      op_str="-:$username"
      ;;
    chpasswd)
      op_str="=:$username:$password"
      ;;
    *)
      error "unknown op"
      ;;
  esac

  local exec_bin="$sys_dir/bin/htpasswd-bulk"

  local user="w_$vhost"

  echo "$op_str" | su -l -c "$exec_bin -c ~/.htpasswd" "$user"
}
