#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action $object [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost to backup

  Refreshes the configuration files of the specified apps, resetting
  database credentials, etc.
"

devpanel_cmd__config_refresh() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $name"
        ;;
      *)
        cmd_args+=( "$name" )
        shift
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  local user="w_$vhost"

  su -l \
    -c "$sys_dir/bin/restore-vhost-subsystem"\ "${cmd_args[*]}"\ -n "$user"
}
