#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action $object [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost to backup
    --file  <filename>      the file where to save the files and database
                            (use - as filename not to save a backup)


  Remove the specified vhost and save the files and database into the specified
  file.
"

devpanel_cmd__vhost_remove() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost file
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --file)
        [ -z "$2" ] && error_missing_value file
        file="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $name"
        ;;
      *)
        cmd_args+=( "$name" )
        shift
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  "$sys_dir/libexec/remove-vhost" "${cmd_args[@]}" $vhost ${file:+$file}
}
