#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action $object [opts] --vhost <vhost> --file <filename>

  Options:
    --vhost <vhost>         the vhost to restore
    --file  <filename>      the file where to restore the vhost from

  Restores a vhost from the specified file. Creates a new vhost.
"

vhost_restore() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost file

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --file)
        [ -z "$2" ] && error_missing_value file
        file="$2"
        shift 2
        ;;
      *)
        error "unknown option $name"
        ;;
    esac
  done

  local param
  for param in vhost file; do
    [ -z "${!param}" ] && error_missing_param $param
  done

  "$sys_dir/libexec/restore-vhost" "$vhost" "$file"
}
