#!/bin/bash
#set -u huponexit

echo -ne "Content-Type: text/plain\n\n"

self_bin=`readlink -e "${BASH_SOURCE[0]}"`
dir=`dirname "$self_bin"`

base_dir=`readlink -e "$dir/../../../.."`

if [ -z "$REMOTE_ADDR" ]; then
  echo "Error: missing IP address. Are you running it manually?" 1>&2
  exit 1
fi

metadata_dir="$base_dir/config/key_value/local"
for meta_link in "$metadata_dir/aws_cluster:vhost:"*; do
  meta_link_base=`basename "$meta_link"`
  if [ "$meta_link_base" == "aws_cluster:vhost:*" ]; then
    break
  fi

  if ! [[ "$meta_link_base" =~ ^aws_cluster:vhost:[A-Za-z0-9_.]+$ ]]; then
    continue
  fi

  vhost=${meta_link_base##*:}
  declare -a domain_list_ar=()
  for domain_meta_link in "$metadata_dir/aws_cluster:vhost:$vhost:domain:"*; do
    domain_link_base=`basename "$domain_meta_link"`
    [ "$domain_link_base" == "aws_cluster:vhost:$vhost:domain:*" ] && break
    domain_name=${domain_link_base##*:}
    domain_list_ar+=( "$domain_name" )
  done

  if [ "${#domain_list_ar[*]}" -gt 0 ]; then
    OLD_IFS="$IFS"
    IFS=","
    echo "$vhost ${domain_list_ar[*]}"
    IFS="$OLD_IFS"
  fi
done

exit 0; exit 0;
