#!/bin/bash
set -u huponexit

echo -ne "Content-Type: text/plain\n\n"

self_bin=`readlink -e "${BASH_SOURCE[0]}"`
dir=`dirname "$self_bin"`

base_dir=`readlink -e "$dir/../../../.."`

tmp_vhost_name="$HTTP_X_VHOST"

if [ -z "$REMOTE_ADDR" ]; then
  echo "Error: missing IP address. Are you running it manually?"
  exit 1
elif [ -z "$tmp_vhost_name" ]; then
  echo "Error: missing vhost name, pass it through the X-VHOST header"
  exit 1
elif [ ${#tmp_vhost_name} -gt 50 ]; then
  echo "Error: vhost name too long"
  exit 1
elif ! [[ "$tmp_vhost_name" =~ ^[A-Za-z0-9.,_-]+$ ]]; then
  echo "Error: invalid vhost name"
  exit 1
fi

vhost_name=$(basename "$tmp_vhost_name")
ip="$REMOTE_ADDR"

( ssh git@localhost "$vhost_name" "$ip" ) &

exit 0; exit 0;
