#!/bin/bash
set -u huponexit

echo -ne "Content-Type: text/plain\n\n"

self_bin=`readlink -e "${BASH_SOURCE[0]}"`
dir=`dirname "$self_bin"`

base_dir=`readlink -e "$dir/../../../.."`

if [ -z "$REMOTE_ADDR" ]; then
  echo "Error: missing IP address. Are you running it manually?" 1>&2
  exit 1
fi

ip="$REMOTE_ADDR"

( ssh git@localhost "$ip" ) &

exit 0; exit 0;
