#!/bin/bash

echo -ne "Content-type: application/tar\n\n"

self_bin=`readlink -e "$0"`
curr_dir=`dirname "$self_bin"`
real_dir=`readlink -e "$curr_dir/../../../.."`

cd "$real_dir"

tar -cf - bin/ lib/functions libexec/ paas-provisioner/aws/
