#!/usr/bin/env perl
use strict;
use warnings;
use CGI;
use FindBin (qw( $RealBin ));
use Cwd (qw( abs_path ));

my $metadir = abs_path($RealBin . "/../../../../config/key_value/local");

my $cgi = CGI->new;

my $rds_db_link    = $metadir . "/aws_cluster_rds_database";
my $rds_host_link  = $metadir . "/aws_cluster_rds_host";
my $rds_port_link  = $metadir . "/aws_cluster_rds_port";
my $rds_user_link  = $metadir . "/aws_cluster_rds_user";
my $rds_pw_link    = $metadir . "/aws_cluster_rds_password";

our $rds_db        = readlink($rds_db_link);
our $rds_host      = readlink($rds_host_link);
our $rds_port      = readlink($rds_port_link);
our $rds_user      = readlink($rds_user_link);
our $rds_password  = readlink($rds_pw_link);

print "Content-type: text/plain\n\n";
no strict 'refs';
foreach my $p (qw(rds_db rds_host rds_port rds_user rds_password)) {
  if(!defined(${$p}) || length(${$p}) == 0) {
    warn "missing variable $p, exiting\n";
    exit(0); # missing a required parameter, exiting
  }
}

print "[client]
database = $rds_db
host = $rds_host
port = $rds_port
user = $rds_user
password = $rds_password
";
