# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 02 Mar 2018 00:14:25 +0000
*               @ALL          1
*               @user         8
