#!/bin/sh
dir=`dirname $0`
dir_bin="$dir/../bin"
vhost="$1"
user="w_$vhost"
label="$2"
error()
{
  echo "ERROR${1+: }$@" >&2
  exit 1
}
case "$0" in
  *-list) action=list;;
  *-transfer) action=transfer;;
  *) error "invalid action";;
esac
# using mode archive: it's OK to operate on a locked vhost
$dir/check-vhost-name archive "$vhost" || exit 1
home="`eval \"echo ~$user\"`" || error
[ -d "$home" ] || error "Home dir $home does not exist"
if [ -n "$label" ]; then $dir/check-archive-pathname -u"$vhost" restore "$home/public_html/gen/archive/$label" || exit 1; fi
echo -n "$label"|su -l -c "$dir_bin/archive-vhost-action $action" "$user"
