#!/bin/sh

# Options:
# -P -- save shadow entry
# -u -- place the archive in ~w_VHOST/gen/archive


exec 3>&1
exec 1>&2

error()
{
  echo "ERROR${1+: }$@" >&2
  exit 1
}

archive_vhost_web_options=""
check_archive_pathname_options=""
opt_u=0

while getopts "Pu" OPTOPT
do
  case "$OPTOPT" in
    P) archive_vhost_web_options="${archive_vhost_web_options+ }-P";;
    u) opt_u=1;;
    *) exit 1;
  esac
done
shift `expr $OPTIND - 1`

dir=`dirname "$0"`
vhost="$1"
archive_dir="$2"
tar_output_file=""
user_db="b_$vhost"
user_web="w_$vhost"
action=archive
[ o`basename $0` = o"remove-vhost" ] && action=remove
KEEP_TMPDIR=0
[ $action = remove ] && KEEP_TMPDIR=1

run()
{
  echo "  Running $@"
  "$@"
}

usage()
{
  echo "Usage: $0 VHOST ARCHIVE_LABEL" >&2
  exit 1
}

$dir/check-vhost-name archive "$vhost" || usage
home="`eval \"echo ~$user_web\"`" || error
[ -d "$home" ] || error "Home dir $home does not exist"

tar_output_file="$archive_dir"

if [ $opt_u = 1 ]
then
  check_archive_pathname_options="${check_archive_pathname_options+ }-u$vhost"
  [ o"`dirname \"$archive_dir\"`" = o"." ] || error "basename without path must be specified with the -u option"
  [ o"`basename \"$archive_dir\"`" = o"$archive_dir" ] || error "basename without path must be specified with the -u option"
  case "$archive_dir" in
  *.tgz);;
  *) error "$archive_dir: only .tgz is allowed with the -u option"
  esac
  archive_dir="$home/public_html/gen/archive/$archive_dir"
fi

if [ o"$archive_dir" != o"-" ]; then  $dir/check-archive-pathname $check_archive_pathname_options archive "$archive_dir" || error; fi


TMPDIR=""

cleanup()
{
  if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]
  then
    if [ $KEEP_TMPDIR = 0 ]
    then
      echo "Removing temporary archive $TMPDIR" >&2
      rm -rf "$TMPDIR"
    fi
  fi
}

TMPDIR=`$dir/archive-mktemp archive-vhost` || exit 1
trap 'cleanup' HUP INT QUIT ILL TRAP ABRT BUS FPE KILL SEGV PIPE STOP ALRM TERM EXIT
archive_dir="$TMPDIR"


echo Processing web...
run mkdir -p "$archive_dir" || exit 1
run $0-web $archive_vhost_web_options "$vhost" "$archive_dir/web" || exit 1
if ! `id -u "$user_db" 2>/dev/null >/dev/null`
then
  echo "Skipping db (no such user $user_db)"
else
  echo Processing db...
  run $0-db "$vhost" "$archive_dir/db"
fi

echo "Making the archive readable to $user_web"
run chmod -R g+rX  "$archive_dir"
#run chgrp -R "$user_web" "$archive_dir"
run chgrp -R "weadmin" "$archive_dir"


if [ -n "$TMPDIR" ] && [ -d "$TMPDIR" ]
then
  exec >&3
  tar -C "$TMPDIR" -zcpf - . | "$dir/archive-vhost-store" $check_archive_pathname_options "$tar_output_file" || error
  if [ $KEEP_TMPDIR = 0 ]
  then
    echo "Removing temporary archive $TMPDIR" >&2
    rm -rf "$TMPDIR"
  fi
fi
