#!/bin/bash

usage() {
  local prog=$(basename "$0")
  cat << EOF

Shows whether the given vhost is password protected or not.
Prints 1 to stdout if it is password protected, and 0 if not protected.

Usage: $prog <vhost>

EOF
  exit 1
}

[ $# -ne 1 ] && usage

dir=`dirname $0`
[ "$dir" == "." ] && dir="$PWD"
dir_bin="$dir/../bin"
vhost="$1"
user="w_$vhost"

# using mode archive: it's OK to operate on a locked vhost
$dir/check-vhost-name archive "$vhost" || exit 1

if ! su -l -c 'egrep -isq "^\s*AuthType" ~/public_html/.htaccess' "$user" \
  && !  su -l -c 'egrep -isq "^\s*AuthType" ~/public_html/'"$vhost"'/.htaccess' "$user"; then
  echo 0
else
  echo 1
fi

exit 0
