#!/bin/bash
dir=`dirname "$0"`
dir_bin="$dir/../bin"
vhost="$1"
user="w_$vhost"
run()
{
  echo "  Running $@"
  "$@"
}
run_su()
{
  echo "  running su -l -c '$@' $user" >&2
  su -l -c "$*" "$user"
}
run_su_ignore_quota()
{
  echo "  running su -l -c '$@' $user" >&2
  "$dir/ignore-quota" "$user" 8 su -l -c "$*" "$user"
}
error()
{
  echo "ERROR${1+: }$@" >&2
  exit 1
}

home()
{
  local user="$1"
  perl -le '@a=getpwnam $ARGV[0] or die "no such user $ARGV[0]\n"; print $a[7]'  "$user"
}

$dir/check-vhost-name lock "$vhost" || error

home=`home "$user"` || error "cannot get $user's home dir"

echo "Disabling apache virtual host"
$dir/lock-vhost-apache "$vhost" || error
echo "Locking user's password"
run "$dir/ignore-quota" "$user" 8 usermod -L "$user" || error
echo "Locking .ssh/authorized_keys"
run_su "$dir_bin/lock-vhost-ssh" || error
echo "Locking crontab"
run_su_ignore_quota "$dir_bin/lock-vhost-crontab" || error
