development: &pgsql
  adapter: postgresql
  database: msf
  username: msf
  password: msf
  host: localhost
  port: 5432
  pool: 256
  timeout: 5

production: &production
  <<: *pgsql

test:
  <<: *pgsql
