#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} <opts>

  Options:
    --vhost <vhost>           the vhost to apply it

    --file <filename>         add vhost include lines from file

    --overwrite               overwrite the current include file with this one

    --no-reload               write the configuration files, but don't
                              reload Apache now

  Add raw Apache configuration lines to the specified vhost.

  Notes:
    - All lines will be added inside the <Virtualhost> section
"

devpanel_cmd__add_vhost_include() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost file
  local tmp_file
  local reload=1 overwrite had_a_include

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;

      --file)
        [ -z "$2" ] && error_missing_value "$name"
        file="$2"
        shift 2
        ;;

      --overwrite)
        overwrite=1
        shift
        ;;

      --no-reload)
        unset reload
        shift
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option '$name'"
        ;;
    esac
  done

  [ -z "$vhost" -o -z "$file" ] && usage

  load_vhost_config "$vhost" || return $?

  if [ -n "$reload" ]; then
    reload_opt=--
  else
    reload_opt=--no-reload
  fi

  if [ "$file" != - -a ! -f "$file" ]; then
    error "missing file '$file'"
  elif [ "$file" != - -a ! -s "$file" ]; then
    error "include file is empty"
  fi

  local config_dir="$lamp__paths__vhosts_config_dir/$vhost/apache"
  local include_file="$config_dir/user_includes.inc"
  local bkp_file="$include_file.bkp"

  if [ -n "$v__vhost__user_includes" -a \
          "$v__vhost__user_includes" == "yes" ]; then

    had_a_include=1

    if [ -z "$overwrite" ]; then
      error "this vhost already has a include file. Please use --ovewrite to replace it." -
      return $?
    fi

    if [ -f "$include_file" ] && ! cp -f "$include_file" "$bkp_file"; then
      error "unable to make a copy of '$include_file'" -
      return $?
    elif [ -f "$bkp_file" ]; then
      temp_files_ar+=( "$bkp_file" )
    fi
  fi

  tmp_file=$(mktemp "$config_dir/tmp_include.XXXXXX")
  if [ $? -eq 0 ]; then
    temp_files_ar+=( "$tmp_file" )
  else
    error "unable to create temp file on $config_dir"
  fi

  if [ "$file" == - ]; then
    cat >"$tmp_file"
  else
    cat "$file" >"$tmp_file"
  fi
  if [ $? -ne 0 ]; then
    error "unable to write to temporary file"
  fi

  local -a set_ar=( "vhost.user_includes = yes" )
  if [ -z "$had_a_include" ]; then
    if ! save_opts_in_vhost_config "$vhost" "${set_ar[@]}"; then
      error "unable to save vhost configuration." -
      return $?
    fi
  fi

  if ! mv -f "$tmp_file" "$include_file"; then
    error "unable to move '$tmp_file' to '$include_file'" -
    return $?
  fi

  if devpanel_run rewrite vhost httpd config --vhost "$vhost" $reload_opt; then
    echo
    echo -n "Successfully added include file."
    if [ -n "$reload" ]; then
      echo
    else 
      echo " Though Apache was not reloaded, as requested."
    fi
  else
    if [ -n "$had_a_include" -a -f "$bkp_file" ]; then
      mv -f "$bkp_file" "$include_file"
    else
      save_opts_in_vhost_config "$vhost" "- vhost.user_includes"
      rm -f "$include_file"
    fi

    echo
    if [ -n "$reload" ]; then
      if devpanel_run rewrite vhost httpd config --vhost "$vhost" $reload_opt; then
        error "failed to add include file. It created an invalid Apache config." -
        return $?
      else
        error "reverted vhost config, but Apache still has problems." -
        return $?
      fi
    fi

    error "failed to generate a valid Apache config file" -
    return $?
  fi

  return 0
}
