#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost> 

  Options:
    --vhost <vhost>         the vhost to backup
    --file  <filename>      the file where to save the files and database
    --key-value key:value   specify some key-value based metadata (accepted
                            format: [A-Za-z0-9_]+:.+ )
    --exclude <filename>    a file name not to include on the archive
                            (relative to the vhost user's \$HOME dir,
                             e.g. ./drush-backups )
    --exclude-from <file>   a file with a list of paths (relative to vhost
                            home) to exclude from the archive

  Creates a backup file with the files and database of a vhost.
"

devpanel_cmd__backup_vhost() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost file
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;

      --file)
        [ -z "$2" ] && error_missing_value file
        file="$2"
        shift 2
        ;;

      --key-value)
        [ -z "$2" ] && error_missing_value $name
        cmd_args+=( -K "$2" )
        shift 2
        ;;

      --exclude)
        [ -z "$2" ] && error_missing_value "$name"
        cmd_args+=( -x "$2" )
        shift 2
        ;;

      --exclude-from)
        [ -z "$2" ] && error_missing_value "$name"
        cmd_args+=( -e "$2" )
        shift 2
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      --[A-Za-z0-9_-]*)
        error "unknown option $name"
        ;;

      *)
        # pass unknown arguments/options to the original command
        cmd_args+=( "$name" )
        shift
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  "$sys_dir/libexec/archive-vhost" "${cmd_args[@]}" $vhost ${file:+$file}
}
