#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost name

  Displays the Apache configuration for the specified virtual host.
"

devpanel_cmd__cat_vhost_config() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local arg vhost linux_user

  while [ -n "$1" ]; do
    arg="$1"
    case "$arg" in
      --vhost)
        [ -z "$2" ] && error_missing_value "$arg"
        vhost="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $arg"
        ;;
      *)
        usage
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost
  
  load_vhost_config "$vhost" || return $?

  if [ -f "$v__vhost__file" ]; then
    cat "$v__vhost__file"
  else
    error "missing file $v__vhost__file" -
    return $?
  fi
}
