#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} <opts>

  Options:
    --vhost <vhost>           the vhost to apply it

  Shows the custom Apache configuration lines from the specified vhost.

  NOTE: to see the full vhost config run: $bin_name cat vhost httpd config
"

devpanel_cmd__cat_vhost_include() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost file
  local -a cmd_args_ar=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option '$name'"
        ;;
    esac
  done

  [ -z "$vhost" ] && usage

  if ! vhost_exists "$vhost"; then
    error "vhost '$vhost' doesn't exist." -
    return $?
  fi

  load_vhost_config "$vhost" || return $?

  if ! is_yes "$v__vhost__user_includes"; then
    echo "Warning: vhost doesn't contain custom user includes" 1>&2
    return 0
  fi

  file="$v__vhost__config_dir/apache/user_includes.inc"

  if [ ! -f "$file" ]; then
    error "missing file '$file'" -
    return $?
  fi

  cat "$file"
}
