#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] <--vhost name>

  Options:
    --vhost <name>      name of the vhost
    --auto-gen          automatically generate and display password,
                        instead of reading from stdin 

  Changes the SFTP/SSH password for the specified vhost. By default reads
  new password from stdin when other options are not specified.
"

devpanel_cmd__change_sftp_password() {

  local arg vhost auto_gen
  local -a cmd_args_ar=( "$sys_dir/libexec/chpass-vhost" )

  [ -z "$1" ] && usage

  while [ -n "$1" ]; do
    arg="$1"
    case "$arg" in
      --vhost)
        [ -z "$2" ] && { error_missing_value "$arg"; return 1; }
        vhost="$2"
        shift 2
        ;;
      --auto-gen)
        auto_gen=1
        shift
        ;;
      --)
        shift
        break
        ;;
      --help)
        usage
        ;;
      *)
        error "unknown option $arg"
        ;;
    esac
  done

  if [ -z "$auto_gen" ]; then
    cmd_args_ar+=( -i -q )
  fi

  "${cmd_args_ar[@]}" "$vhost"
}
