#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action <--vhost name>

  Options:
    --vhost <name>            name of the vhost
    --generate                automatically generate a new password

  Change the password that the vhost uses to connect on MySQL.
"

devpanel_cmd__change_vhost_password_on_mysql() {
  local opt vhost instance sql_query generate ini_file mysql_user
  local new_password new_password_esc
  local -a info_ar=()
  
  [ $# -eq 0 -o -z "$1" ] && usage

  while [ -n "$1" ]; do
    opt="$1"

    case $opt in
      --vhost)
        [ -z "$2" ] && error_missing_value $opt
        vhost="$2"
        shift 2
        ;;

      --generate)
        generate=yes
        shift 1
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option: $opt" -
        return $?
        ;;
    esac
  done

  [ -z "$vhost" ] && usage

  load_vhost_config "$vhost" || return $?

  if [ -n "$v__mysql__instance" ]; then
    instance="$v__mysql__instance"
  else
    error "this vhost is not associated to any MySQL instance" -
    return $?
  fi

  if ! mysql_instance_exists "$instance"; then
    error "there's no instance with this name" -
    return $?
  fi

  load_mysql_instance_config "$instance" || return $?

  mysql_ping_instance "$instance" >/dev/null || return $?

  if [ "$generate" == yes ] ; then
    new_password=$(gen_random_str_az09_lower 15)
  else
    if ! read -s -p "Enter password (stdin): " new_password; then
      error "ended without changing password" -
      return $?
    fi
    echo ; echo
  fi

  if [ -z "$new_password" ]; then
    error "got an empty password" -
    return $?
  fi

  mysql_user="$v__vhost__linux_user"
  mysql_change_user_password --instance "$instance" --user "$mysql_user" \
    --password "$new_password"
  if [ $? -eq 0 ]; then
    if [[ "$new_password" =~ [^a-z0-9A-Z_,.-] ]]; then
      new_password_esc=$(escape_quotes "$new_password" )
    else
      new_password_esc="$new_password"
    fi

    mysql_create_vhost_cnf --vhost "$vhost" --my-cnf "$v__mysql__client_file" \
                           --user  "$v__vhost__linux_user"                    \
													 --instance "$instance" --password "$new_password_esc"

    if ! devpanel_run refresh app config --vhost "$vhost"; then
      echo
      echo "Warning: password updated, but failed to refresh app files.  You'll need to fix the app's config files manually" 1>&2
      echo
    fi

    echo
    echo "Successfully changed vhost password on MySQL."
  else
    error "failed to change vhost password on MySQL." -
    return $?
  fi
}
