#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost> --from <source>

  Options:
    --vhost <vhost>           name of the vhost

    --from  <source>          source from where to create the app
                              (can be a filename or url for the tar ball)

    --dedicated-mysql         create a new dedicated MySQL instance

    --skip-mysql              don't do any MySQL configuration for this vhost

    --mysql-instance name     use an existing MySQL instance as the MySQL
                              server

    --title <site_title>      sets the website title for the apps that
                              support it

    --desc <description>      a short description of the vhost's purpose

    --password-stdin          read app password from STDIN

    --php-version <version>   the PHP version to use on this vhost (e.g.: 5, 7)

    --no-summary              don't print the summary information after
                              creating the vhost

    --subsystem <name>        name of the app subsystem (e.g. drupal,
                              wordpress, etc)

    --db-name name            name of the main database of the app

    --dont-config-app         only extract the files, don't try to configure
                              the app internals

    --config-function name    name of the config function to run to setup
                              the app

    --install-profile name    name of the install profile for apps that
                              support different profiles on install

  Creates a new vhost from the specified source.
"

# main
devpanel_cmd__create_vhost() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost from source_type title desc
  local branch app_password read_pw_stdin php_version subsystem
  local source_type publisher uri_part app_url mysql_instance db_name
  local dedicated_mysql with_mysql=yes
  local st_archive_extracted st_extracted_dir
  local print_summary=yes do_config_app=yes
  local -a cmd_args=() lamp_cmd_args=() app_cmd_ar=() restore_cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --from)
        [ -z "$2" ] && error_missing_value from
        from="$2"
        shift 2
        ;;

      --title)
        [ -z "$2" ] && error_missing_value title
        title="$2"
        app_cmd_ar+=( --site-title "$title" )
        shift 2
        ;;

      --php-version)
        [ -z "$2" ] && error_missing_value "$name"
        php_version="$2"
        shift 2
        ;;

      --dedicated-mysql)
        dedicated_mysql=yes
        if ! is_var_set_to_yes with_mysql; then
          error "conflicting mysql options on command line" -
          return $?
        fi

        lamp_cmd_args+=( $name )
        shift
        ;;

      --mysql-instance)
        [ -z "$2" ] && error_missing_value "$name"

        if ! is_var_set_to_yes with_mysql; then
          error "conflicting mysql options on command line" -
          return $?
        fi

        mysql_instance="$2"
        lamp_cmd_args+=( "$name" "$mysql_instance" )
        shift 2
        ;;

      --skip-mysql)
        if [ -n "$dedicated_mysql" ]; then
          error "can't use $name with --dedicated-mysql at the same time" -
          return $?
        elif [ -n "$mysql_instance" ]; then
          error "can't use $name with --mysql-instance at the same time" -
          return $?
        fi

        unset with_mysql
        shift
        ;;

      --help)
        usage
        ;;

      --desc)
        [ -z "$2" ] && error_missing_value "$name"
        desc="$2"
        lamp_cmd_args+=( --description "$desc" )
        shift 2
        ;;

      --password-stdin)
        read_pw_stdin=1
        shift
        ;;

      --no-summary)
        unset print_summary
        shift
        ;;

      --subsystem)
        [ -z "$2" ] && error_missing_value "$name"
        if is_known_seedapp_subsystem "$2"; then
          subsystem="$2"
        else
          error "unknown subsystem" -
          return 1
        fi

        shift 2
        ;;

      --db-name)
        [ -z "$2" ] && error_missing_value "$name"
        db_name="$2"
        shift 2
        ;;

      --config-function|--install-profile)
        [ -z "$2" ] && error_missing_value "$name"
        if [[ "$2" =~ ^[A-Za-z0-9_-]+$ ]]; then
          app_cmd_ar+=( "$name" "$2" )
        else
          error "invalid format for parameter $name" -
          return $?
        fi
        shift 2
        ;;

      --dont-config-app)
        unset do_config_app
        shift
        ;;

      --[A-Za-z0-9_-]*)
        error "unknown argument $name"
        ;;
      *)
        # pass unknown arguments/options to the original command
        cmd_args+=( "$name" )
        shift
        ;;

      # --database)
      #   got_r[database]="$2"
      #   shift 2
      #   ;;
      # --engine)
      #   got_r[engine]="$2"
      #   shift 2
      #   ;;
      # --name)
      #   got_r[vhost]="$2"
      #   shift 2
      #   ;;

    esac
  done

  [ -z "$vhost" ]  && error_missing_param vhost
  [ -z "$from" ]   && error_missing_param from

  if ! is_valid_vhost_string --strict-length-check "$vhost"; then
    error "invalid string format for vhost name" -
    return $?
  fi

  if vhost_exists "$vhost"; then
    error "there's already a vhost with this name." -
    return $?
  fi

  if st_extracted_dir=$(mktemp -d "$conf__paths__temp_dir/vhost_extract.XXXXXX"); then
    temp_dirs_ar+=( "$st_extracted_dir" )
  else
    echo "$FUNCNAME(): failed to create temporary dir" 1>&2
    return 1
  fi

  # detect the source type
  # e.g. devpanel://wordpress-v4, webenabled://drupal-v7
  #      http://...
  if [[ "$from" =~ ^([a-z0-9]+)://.+$ ]]; then
    source_type=url

    # check if it's a short hand publisher://name url
    # and then translate it
    if [[ "$from" =~ ^([a-z0-9]+)://[A-Za-z0-9-]+$ ]] && \
       ! in_array "$source_type" file ftp http https; then

      publisher=${from%%://*}
      uri_part=${from#*://}
      if is_known_seedapp_publisher "$publisher"; then
        if ! app_url=$(get_tarball_url_for_app "$uri_part" "$publisher"); then
          return 1
        fi
      else
        error "unknown publisher '$publisher'" -
        return 1
      fi
    else
      # otherwise, treat it as a url to be passed directly to curl
      app_url="$from"
    fi
  elif [ "$from" == - ]; then
    source_type=stdin
  else
    # by default let's assume the source is a file
    source_type=file
  fi

  if [ -n "$read_pw_stdin" ]; then
    read -p "Enter app password (stdin): " app_password
    if [ -z "$app_password" ]; then
      error "got an empty password on stdin" -
      return 1
    fi
  fi

  local st

  if [ -n "$php_version" ]; then
    cmd_args+=( -T "$php_version" )
  fi

  if [ -n "$from" ]; then
    case $source_type in
      file)
        if [ -f "$from" ]; then
          src_archive="$from"
        else
          error "file not found" -
          return 1
        fi
        ;;

      stdin)
        if [ -t 0 ]; then
          echo "Reading archive file from STDIN..." 1>&2
        fi

        if tar --no-same-owner -zxpSf - -C "$st_extracted_dir"; then
          st_archive_extracted=yes
        else
          echo "$FUNCNAME(): failed to extract archive from STDIN..." 1>&2
          return 1
        fi

        ;;

      url)
        download_file "$app_url" - | \
          tar --no-same-owner -zxpSf - -C "$st_extracted_dir"

        if [ $? -eq 0 ]; then
          st_archive_extracted=yes
        else
          echo "$FUNCNAME(): failed to extract tar ball from url" 1>&2
          return 1
        fi
        ;;

        *)
        error "don't know how to handle --from value '$from' (not an existing file nor a url)" -
        return $?
        ;;
      esac
  fi # // if [ -n $from ]

  if is_yes "$st_archive_extracted"; then
    local _tmp_app_ini="$st_extracted_dir/.devpanel/app.ini"
    if [ -f "$_tmp_app_ini" ] && ! read_ini_file_into_namespace "$_tmp_app_ini" src; then
      echo "$FUNCNAME(): failed to read from '$_tmp_app_ini'" 1>&2
      return 1
    fi
  else
    echo "Extracting metadata from file '$src_archive'..."
    read_devpanel_ini_from_app_archive --missing-ok "$src_archive" || \
      return $?
  fi

  if [ -n "$subsystem" ]; then
    src__app__subsystem="$subsystem"
  else
    if [ -n "$src__app__subsystem" ]; then
      subsystem="$src__app__subsystem"
    else
      # guess app type when --subsystem not specified
      if is_yes "$st_archive_extracted"; then
        if guess_subsystem_from_database_filelist "$st_extracted_dir/db/databases"; then
          subsystem="$_dp_value"
        fi
      else
        if guess_subsystem_from_app_archive "$src_archive"; then
          subsystem="$_dp_value"
        fi
      fi

      if [ -z "$subsystem" ]; then
        error "couldn't detect the subsystem of the app. Please specify it on command line." -
        return $?
      fi
    fi
  fi

  if is_known_seedapp_subsystem "$subsystem"; then
    lamp_cmd_args+=( --subsystem "$subsystem" )
  else
    error "got an unknown app subsystem: $subsystem" -
    return $?
  fi

  if is_var_set_to_yes src__mysql__skip; then
    unset with_mysql
  fi

  if [ -n "$php_version" ]; then
    src__php__version="$php_version"
    lamp_cmd_args+=( --php-version "$php_version" )
  elif [ -n "$src__php__version" ]; then
    php_version="$src__php__version"
    lamp_cmd_args+=( --php-version "$php_version" )
  fi

  if is_var_set_to_yes with_mysql; then
    if [ -n "$db_name" ]; then
      lamp_cmd_args+=( --db-name "$db_name" )
      src__app__database_name="$db_name"
    elif [ -n "$src__app__database_name" ]; then
      db_name="$src__app__database_name"
      lamp_cmd_args+=( --db-name "$db_name" )
    fi
  else
    lamp_cmd_args+=( --skip-mysql )
  fi

  if ! devpanel_run create lamp vhost "${lamp_cmd_args[@]}" --vhost "$vhost" \
         --subsystem "$subsystem" --dont-activate-now; then

    error "failed to create lamp vhost" -
    return $?
  fi

  if [ "$source_type" == "file" ]; then
    restore_cmd_args+=( --filename "$src_archive" )
  else
    restore_cmd_args+=( --from-dir "$st_extracted_dir" )
  fi

  if ! devpanel_run restore backup --vhost "$vhost" --dont-remove-files \
       "${restore_cmd_args[@]}" --dont-disable-vhost --quiet; then
    error "failed to extract the contents of tar ball" -
    return $?
  fi

  if [ -n "$do_config_app" ]; then
    app_cmd_ar+=( --first-setup )
    devpanel_run config app "${app_cmd_ar[@]}" --vhost "$vhost" || return $?

    if [ -n "$app_password" ]; then
      echo "$app_password" | devpanel_run reset app password --vhost "$vhost"
      if [ $? -ne 0 ]; then
        echo "Warning: failed setting the password for app..." 1>&2
      fi
    fi
  fi

  if ! load_vhost_config "$vhost"; then
    echo "Warning: unable to load config for the newly created vhost" 1>&2
  fi

  if ! devpanel_run rewrite vhost httpd config --vhost "$vhost"; then
    echo "Warning: vhost created, but failed to write Apache config" 1>&2
    [ -t 0 ] && sleep 2
  fi

  [ -n "$print_summary" ] && print_vhost_summary "$vhost"

  if [ -z "$do_config_app" ]; then
    echo "NOTE: as requested, the app internal config was not initialized."
    echo
  fi

  echo "Successfully created vhost $vhost"
}
