#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --yes

  Options:
    --yes                   confirm the intent to debug

  Stops the running taskd (if any) and starts taskd in foreground in debug
  mode.
"

devpanel_cmd__debug_taskd() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name confirmed

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --yes)
        confirmed=1
        shift
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option $name" - 
				return $?
        ;;
    esac
  done

  if [ -z "$confirmed" ]; then
    error_missing_param yes
    return 1
  fi

  devpanel_run stop taskd --yes

  $sys_dir/sbin/taskd -F -d

  echo
  echo "Note: remember to restart taskd if you want it to keep running."
}
