#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost          <vhost>             name of the vhost

  Disables Let's Encrypt on the specified vhost.
"

# main
devpanel_cmd__disable_lets_encrypt() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --)
        shift
        break
        ;;
      *)
        error "unknown argument $name"
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  "$sys_dir/libexec/lets-encrypt-wrapper" disable "$vhost"
}
