#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts]

  Options:
    --yes                 confirm disabling long names

  Disallow creating vhosts with names longer than 6 characters.
"

devpanel_cmd__disable_long_vhost_names() {
  local name confirmed

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --yes)
        confirmed=yes
        shift
        ;;
      --help|*)
        usage
        ;;
    esac
  done

  [ -z "$confirmed" -o "$confirmed" != yes ] && usage

  disable_long_vhost_names
  if [ $? -eq 0 ]; then
    echo "Successfully disabled long vhost names."
  else
    error "failed to update metadata for long vhost names." -
    return $?
  fi
}
