#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost          <vhost>             name of the vhost

  Disables SSL on the specified vhost.
"

# main
devpanel_cmd__disable_ssl() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --)
        shift
        break
        ;;
      *)
        error "unknown argument $name"
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  if ! vhost_exists "$vhost"; then
    exit 1
  fi

  if is_lets_encrypt_enabled_for_vhost "$vhost"; then
    devpanel_run disable lets-encrypt --vhost "$vhost"
  else
    "$sys_dir/libexec/disable-ssl-config" "${cmd_args[@]}" "$vhost"
  fi
}
