#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost to protect

  Disables htpasswd protection on the specified vhost.
"

devpanel_cmd__disable_htpasswd() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost file
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;

      --)
        shift
        break
        ;;

      --help)
        usage
        ;;

      *)
        error "unknown option $name"
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  load_vhost_config "$vhost" || return $?

  if ! is_vhost_enabled "$vhost"; then
    error "can't disable htpasswd on a vhost that is disabled" -
    return $?
  fi

  if ! is_htpasswd_enabled_on_vhost "$vhost" ; then
    echo "Warning: htpasswd is already disabled for vhost '$vhost'" 1>&2
    return 0
  fi

  save_opts_in_vhost_config "$vhost" "vhost.htpasswd = no" || return $?

  rewrite_vhost_apache_config "$vhost"
}
