#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost to protect

  Disables FastCGI on the specified vhost.
"

devpanel_cmd__disable_fastcgi() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $name"
        ;;
      *)
        usage
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  if ! is_fastcgi_enabled_on_vhost "$vhost"; then
    echo "Warning: FastCGI is not enabled on vhost $vhost" 1>&2
    return 0
  fi

  metadata_str="rm apache_vhost:0:include:fastcgi"

  echo "$metadata_str" | "$DEVPANEL_HOME/libexec/apache-metadata-handler" \
                           -q "$vhost"
  local st=$?
  if [ $st -ne 0 ]; then
    error "unable to write vhost metadata" -
  fi

  devpanel_run rewrite vhost config --vhost "$vhost"
  if [ $? -eq 0 ]; then
    echo
    echo "Successfully disabled FastCGI on vhost $vhost."
  else
    echo
    error "failed to disable FastCGI on vhost $vhost." -
    return 1
  fi

  return $st
}
