#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost to protect

  Disables FastCGI on the specified vhost.
"

devpanel_cmd__disable_fastcgi() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option $name"
        ;;

    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  load_vhost_config "$vhost" || return $?

  if ! is_fastcgi_enabled_on_vhost "$vhost"; then
    echo "Warning: FastCGI is not enabled on vhost $vhost" 1>&2
    return 0
  fi

  save_opts_in_vhost_config "$vhost" "vhost.fastcgi = no" || return $?

  rewrite_vhost_apache_config "$vhost"
  if [ $? -eq 0 ]; then
    echo
    echo "Successfully disabled FastCGI on vhost $vhost."
  else
    echo
    error "failed to disable FastCGI on vhost $vhost." -
    return 1
  fi
}
