#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts]

  Options:
    --yes                 confirm disabling of updates

  Disables automated updates of the Linux distribution on the
  current server.
"

devpanel_cmd__disable_distro_updates() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name confirmed
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --yes)
        confirmed=yes
        shift
        ;;
      --help|*)
        usage
        ;;
    esac
  done

  [ -z "$confirmed" -o "$confirmed" != yes ] && usage

  if save_opts_in_devpanel_config "distro.updates_enabled = no"; then
    echo "Successfully disabled distro updates."
  else
    error "unable to save config file" -
  fi
}
