#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost to protect

  Disables the specified vhost.
"

devpanel_cmd__disable_vhost() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost user
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option $name"
        ;;
    esac
  done

  [ -z "$vhost" ] && error_missing_param vhost

  load_vhost_config "$vhost" || return $?

  vhost_exists_and_is_enabled "$vhost" || return $?

  user="$v__vhost__linux_user"

  if "$sys_dir/libexec/ignore-quota" "$user" 8 \
       usermod -L "$user"; then
    echo "Locking user's password"
  else
    error "failed to lock user password" -
    return $?
  fi

  if "$sys_dir/libexec/ignore-quota" "$user" 8 \
       su -l -c "$sys_dir/bin/lock-vhost-ssh" "$user"; then
    echo "Locked .ssh/authorized_keys"
  else
    error "failed to lock ssh password" -
    return $?
  fi

  if "$sys_dir/libexec/ignore-quota" "$user" 8 \
       su -l -c "$sys_dir/bin/lock-vhost-crontab" "$user"; then

    echo "Locked crontab"
  else
    error "failed locking crontab" -
    return $?
  fi

  rewrite_vhost_apache_config --disable "$vhost" || return $?

  save_opts_in_vhost_config "$vhost" "vhost.enabled = no" || return $?
}
