#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost where to enable FastCGI

  Enables FastCGI on the specified vhost.
"

devpanel_cmd__enable_fastcgi() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && { error_missing_value "$name" ; return $?; }
        vhost="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $name" - 
				return $?
        ;;
      *)
				usage
        ;;
    esac
  done

  [ -z "$vhost" ] && { error_missing_param vhost; return $?; }

  metadata_str="set apache_vhost:0:include:fastcgi fastcgi"

  if is_fastcgi_enabled_on_vhost "$vhost"; then
    echo "Warning: FastCGI is already enabled on vhost $vhost." 1>&2
    return 0
  else
    echo "$metadata_str" | "$DEVPANEL_HOME/libexec/apache-metadata-handler" \
                           -q "$vhost"
    if [ $? -ne 0 ]; then
      error "unable to write vhost metadata" -
      return 1
    fi
  fi

  devpanel_run rewrite vhost config --vhost "$vhost"
  if [ $? -eq 0 ]; then
    echo
    echo "Successfully enabled FastCGI on vhost $vhost."
  else
    echo
    error "failed to enable FastCGI on vhost $vhost." -
    return 1
  fi
}
