#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost where to enable FastCGI

  Enables FastCGI on the specified vhost.
"

devpanel_cmd__enable_fastcgi() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && { error_missing_value "$name" ; return $?; }
        vhost="$2"
        shift 2
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option $name" - 
				return $?
        ;;
    esac
  done

  [ -z "$vhost" ] && { error_missing_param vhost; return $?; }

  save_opts_in_vhost_config "$vhost" "vhost.fastcgi = yes" || return $?

  rewrite_vhost_apache_config "$vhost"
  if [ $? -eq 0 ]; then
    echo
    echo "Successfully enabled FastCGI on vhost $vhost."
  else
    echo
    error "failed to enable FastCGI on vhost $vhost." -
    return 1
  fi
}
