#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action $object

  Prints server information.
"

devpanel_cmd__get_server_info() {
  local info_txt
  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $name"
        ;;
      *)
        break
        ;;
    esac
  done

  local linux_distro vhosts_domain apache_vhosts_port distro_updates_st
  local -a vhosts_ar
  local -i n_vhosts=0

  linux_distro=$(get_linux_distro_string 2>/dev/null)
  vhosts_domain=$(get_server_base_domain)
  apache_vhosts_port=$(get_apache_vhosts_port)
  vhosts_ar=( $(get_list_of_vhosts) )
  n_vhosts=${#vhosts_ar[@]}

  if is_distro_updates_enabled; then
    distro_updates_st=enabled
  else
    distro_updates_st=disabled
  fi

  info_txt="Linux Distribution: $linux_distro
Vhosts base domain: $vhosts_domain
Apache Vhosts Port: $apache_vhosts_port
Number of vhosts: $n_vhosts
Distro Updates: $distro_updates_st"

  echo "$info_txt"
}
