#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --hostname <hostname>

  Options:
    --hostname <name>       the base hostname for virtualhosts

  Initializes the basic config of a devPanel installation.
"

devpanel_cmd__init_config() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local arg hostname

  while [ -n "$1" ]; do
    arg="$1"
    case "$arg" in
      --hostname)
        [ -z "$2" ] && error_missing_value hostname
        hostname="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $arg"
        ;;
      *)
        usage
        ;;
    esac
  done

  [ -z "$hostname" ] && usage

  devpanel_run update

  devpanel_run set base hostname --name "$hostname"
}
