#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts]

  Options:
    --publisher <name>         publisher of the application
    --app <name>               the name of the application to install
    --vhost <name>             the name of the vhost where to install
    --desc <description>       a short description of the apps's purpose

  Installs the specified application in a new virtual host.
"

devpanel_cmd__install_app(){
  [ -z "$1" ] && usage

  local name vhost arg publisher app app_url desc
  local -a cmd_args=()

  while [ -n "$1" ]; do
    arg="$1"
    case "$arg" in
      --publisher)
        [ -z "$2" ] && { error_missing_value "$arg"; return $?; }
        if [[ "$2" =~ ^[A-Za-z0-9_]+$ ]]; then
          publisher="$2"
          shift 2
        else
          error "invalid format for publisher name"
        fi
        ;;

      --app)
        [ -z "$2" ] && { error_missing_value "$arg"; return $?; }
        app="$2"
        shift 2
        ;;

      --vhost)
        [ -z "$2" ] && { error_missing_value "$arg"; return $?; }
        vhost="$2"
        shift 2
        ;;

      --desc)
        [ -z "$2" ] && error_missing_value "$name"
        desc="$2"
        shift 2
        ;;

      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $name"
        ;;
      *)
        usage
        ;;
    esac
  done

  [ -z "$app" ] && error_missing_param app

  if [ -z "$vhost" ]; then
    vhost=$(gen_random_str_az_lower 6)
  fi

  if [ -z "$publisher" ]; then
    publisher=$(get_default_app_publisher) || return $?
  fi

  "$sys_dir/libexec/check-vhost-name" restore "$vhost" || return $?

  local app_url
  app_url=$(get_tarball_url_for_app "$app" "$publisher") || return $?

  devpanel_run create vhost --vhost "$vhost" --from "$app_url" \
    ${desc:+--desc "$desc"}

  if [ $? -eq 0 ]; then
    echo
    echo "Successfully installed $app."
  else
    echo
    error "unable to install app '$app' from publisher '$publisher'." -
  fi
}
