#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Lists the vhosts on this server.
"

devpanel_cmd__list_vhosts() {
  local vhost vhosts_ar name app default_host url

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --help)
        usage
        ;;
      *)
        usage
        ;;
    esac
  done


  vhosts_ar=( $(get_list_of_vhosts) )

  if [ ${#vhosts_ar[@]} -eq 0 ]; then
    echo "No vhost on this server."
    return 0
  fi

  local format_str
  
  if is_longer_vhost_names_enabled; then
    format_str="%-16s %-40s %-35s\n"
  else
    format_str="%-8s %-40s %-35s\n"
  fi

  printf "$format_str\n" Vhost Domain Description
  for vhost in ${vhosts_ar[@]}; do
    domain=$(get_vhost_default_hostname "$vhost")
    desc=$(get_vhost_description "$vhost")
    desc="${desc:-(no description set)}"

    # printf "  vhost: %-8s domain: %-40s desc: %-35s\n" \
     printf "$format_str" "$vhost" "$domain" "$desc"
  done

  echo
}
