#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action <--instance <name> | --vhost <vhost> | --domain <domain>>

  Options:
    --instance <name>        name of the mysql instance

  Alternative Options
    --vhost  <vhost>         the vhost
    --domain <domain>        find the vhost associated with the
                             specified domain


  NOTE: either --vhost, --domain or --instance needs to be specified (and
        only one of it should be specified).

  Returns the result of a ping to the mysql instance.
"

devpanel_cmd__ping_mysql_instance() {
  local param vhost domain instance
  
  [ $# -eq 0 -o -z "$1" ] && usage

  while [ -n "$1" ]; do
    param="$1"

    case $param in
      --instance)
        [ -z "$2" ] && error_missing_value "$param"
        instance="$2"
        shift 2
        ;;

      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --domain)
        [ -z "$2" ] && error_missing_value domain
        domain="$2"
        shift 2
        ;;

      --help)
        usage
        ;;
      --)
        shift
        break
        ;;
      *)
        error "unknown parameter: $param"
        ;;
    esac
  done

  local _opt
  local -i opt_n
  for _opt in instance vhost domain; do
    if [ -n "${!_opt}" ]; then
      opt_n+=1
      if [ $opt_n -gt 1 ]; then
        error "options --instance, --vhost and --domain are mutually exclusive." -
        return $?
      fi
    fi
  done

  if [ -n "$domain" ]; then
    if ! vhost=$(get_vhost_with_hostname "$domain"); then
      error "couldn't find a vhost for domain." -
      return $?
    fi
  fi

  if [ -n "$vhost" ]; then
    load_vhost_config "$vhost" || return $?
    if [ -n "$v__mysql__instance" ]; then
      instance="$v__mysql__instance"
    else
      error "vhost not associated to any mysql instance" -
      return $?
    fi
  fi

  if [ -n "$instance" ]; then
    load_mysql_instance_config "$instance" || return $?
  else
    error "unable to find mysql instance" -
    return $?
  fi

  mysql_ping_instance "$instance"
}
