#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} <opts>

  Options:
    --vhost <vhost>           the vhost to apply it

    --no-reload               write the configuration files, but don't
                              reload Apache now

  Remove custom Apache configuration lines from the specified vhost.
"

devpanel_cmd__remove_vhost_include() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost include_file
  local -a cmd_args_ar=()
  local reload=1

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;

      --no-reload)
        unset reload
        cmd_args_ar+=( -N )
        shift
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option '$name'"
        ;;
    esac
  done

  [ -z "$vhost" ] && usage

  if ! vhost_exists "$vhost"; then
    error "vhost '$vhost' doesn't exist." -
    return $?
  fi

  if ! has_user_includes "$vhost"; then
    echo "Warning: vhost doesn't contain custom user includes" 1>&2
    return 0
  fi

  include_file=$(get_vhost_include_filename "$vhost" ) || return $?

  if unset_user_include_metadata "$vhost" user_includes; then
    rm -f "$include_file"
    devpanel_run rewrite vhost config --vhost "$vhost" --no-restart
    if [ -n "$reload" ]; then
      if ! apache_ctl reload; then
        echo "Warnings: removed vhost includes, but Apache reload failed" 1>&2
        return 0
      fi
    fi

    echo "Successfully removed custom Apache includes from vhost $vhost."
    return 0
  else
    error "unable to disable vhost includes"
  fi
}
