#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} <opts>

  Options:
    --vhost <vhost>           the vhost to apply it

    --no-reload               write the configuration files, but don't
                              reload Apache now

  Remove custom Apache configuration lines from the specified vhost.
"

devpanel_cmd__remove_vhost_include() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost include_file
  local -a cmd_args_ar=()
  local reload=1 reload_opt=--

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;

      --no-reload)
        unset reload
        reload_opt=--no-reload
        shift
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option '$name'"
        ;;
    esac
  done

  [ -z "$vhost" ] && usage

  load_vhost_config "$vhost" || return $?

  if [ -z "$v__vhost__user_includes" -o \
          "$v__vhost__user_includes" != yes ]; then
    echo "Warning: vhost doesn't contain custom user includes" 1>&2
    return 0
  fi

  if save_opts_in_vhost_config "$vhost" "- vhost.user_includes"; then
    rm -f "$v__vhost__user_include_file"
    if devpanel_run rewrite vhost config --vhost "$vhost" $reload_opt; then
      echo
      echo "Successfully removed user includes for vhost '$vhost'."
    else
      echo
      echo "Warning: removed include file, but failed to reload Apache" 1>&2
    fi
  else
    error "unable to update config file." -
    return $?
  fi

  return 0
}
