#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost> --file <filename>

  Options:
    --vhost <vhost>         the vhost to backup
    --file  <filename>      the name of the file to remove

  Removes a backup file from the specified vhost.
"

devpanel_cmd__remove_backup() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost file var
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && error_missing_value "$name"
        vhost="$2"
        shift 2
        ;;

      --file)
        [ -z "$2" ] && error_missing_value "$name"
        file="$2"
        shift 2
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option $name" -
        return $?
        ;;

    esac
  done

  for var in vhost file ; do
    [ -z "${!var}" ] && error_missing_param $var
  done

  load_vhost_config "$vhost" || return $?

  if ! does_vhost_archive_file_exist "$file"; then
    error "couldn't find a file for '$file'" -
    return $?
  fi

  if rm_vhost_archive "$file"; then
    echo "Successfully removed file '$file'"
  else
    error "unable to remove file '$file'" -
    return $?
  fi
}
