#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action [opts] --yes

  Options:
    --conditional            don't start if it's not running

  Restarts Apache httpd.
"

devpanel_cmd__restart_apache() {
  local param conditional confirmed

  [ $# -eq 0 -o -z "$1" ] && usage

  while [ -n "$1" ]; do
    param="$1"

    case $param in
      --yes)
        confirmed=yes
        shift
        ;;

      --conditional)
        conditional=yes
        shift
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown parameter: $param" -
        return $?
        ;;
    esac
  done

  [ -z "$confirmed" ] && usage

  if [ -n "$conditional" -a "$conditional" == yes ]; then
    if ! is_apache_running; then
      return 0
    fi
  else
    restart_apache
  fi
}
