#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action [opts] [--vhost <vhost>] [--domain <domain>]

  Options:
    --vhost  <vhost>          the vhost
    --domain <domain>         find the vhost associated with the
                              specified domain
    --conditional             only try to restart if the vhost is enabled

  Restarts mysqld associated with the specified domain or vhost.
"

devpanel_cmd__restart_mysql() {
  local param vhost domain vhost_user db_user  
  local conditional
  [ $# -eq 0 -o -z "$1" ] && usage

  while [ -n "$1" ]; do
    param="$1"

    case $param in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --domain)
        [ -z "$2" ] && error_missing_value domain
        domain="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      --)
        shift
        break
        ;;
      --conditional)
        conditional=1
        shift
        ;;
      *)
        error "unknown parameter: $param"
        ;;
    esac
  done

  if [ -z "$vhost" -a -z "$domain" ]; then
    error "either --vhost or --domain needs to be specified"
  fi

  if [ -z "$vhost" ]; then
    vhost=$(get_vhost_with_hostname "$domain")
    if [ $? -ne 0 ]; then
      error "didn't find any vhost with the specified hostname"
    fi
  fi

  if ! vhost_exists "$vhost"; then
    error "vhost doesn't exist."
  fi

  load_vhost_config "$vhost" || return $?
  vhost_user="$v__vhost__linux_user"

  if [ -n "$conditional" ]; then
    if ! is_vhost_enabled "$vhost"; then
      return 0
    fi
  fi

  db_user="b_${vhost_user#w_}"

  local actions_bin="$sys_dir/compat/dbmgr/current/bin/daemon-action"

  "$actions_bin" stop-politely-or-force "$db_user"

  echo "Starting mysql for vhost $vhost..."
  echo -n "  "
  "$actions_bin" start "$db_user"
  if [ $? -eq 0 ]; then
    return 0
  else
    error "unable to start mysql for vhost $vhost"
  fi
}
