#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost where to rewrite the config
    --no-restart            don't restart/reload the web server

  Rewrite the vhost config to apply the configuration updates.
"

devpanel_cmd__rewrite_vhost_config() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && { error_missing_value "$name" ; return $?; }
        vhost="$2"
        shift 2
        ;;
      --no-restart)
        cmd_args+=( -n )
        shift
        ;;

      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $name" - 
				return $?
        ;;
      *)
				usage
        ;;
    esac
  done

  [ -z "$vhost" ] && { error_missing_param vhost; return $?; }

  if ! vhost_exists "$vhost"; then
    exit 1
  fi

  "$sys_dir/libexec/config-vhost-apache" "${cmd_args[@]}" "$vhost"
}
