#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --vhost <vhost>

  Options:
    --vhost <vhost>         the vhost where to rewrite the config
    --no-restart            don't restart/reload the web server

  Rewrite the vhost config to apply the configuration updates.
"

devpanel_cmd__rewrite_vhost_httpd_config() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && { error_missing_value "$name" ; return $?; }
        vhost="$2"
        shift 2
        ;;
      --no-restart)
        cmd_args+=( -n )
        shift
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option $name" - 
        return $?
        ;;
    esac
  done

  [ -z "$vhost" ] && { error_missing_param vhost; return $?; }

  vhost_exists "$vhost" || return $?

  "$sys_dir/libexec/rewrite-vhost-config" "${cmd_args[@]}" "$vhost"
}
