#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --yes [--vhost <vhost>]
                                              [--freq <freq>]

  Options:
    --vhost <vhost>         the vhost where to rewrite the config
    --freq  <frequency>     the frequency of the snapshots
    --yes                   confirms the intent to really run it

  Runs the scheduled backup snapshots for virtual hosts.
"

devpanel_cmd__run_scheduled_snapshots() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost confirmed
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && { error_missing_value "$name" ; return $?; }
        vhost="$2"
        shift 2
        ;;

      --freq)
        [ -z "$2" ] && { error_missing_value "$name" ; return $?; }
        freq="$2"
        shift 2
        ;;

      --yes)
        confirmed=1
        shift
        ;;

      --help)
        usage
        ;;

      --[A-Za-z0-9_-]*)
        error "unknown option $name" - 
				return $?
        ;;
      *)
				usage
        ;;
    esac
  done

  [ -z "$confirmed" ] && usage

  if [ -n "$vhost" -a -z "$freq" ]; then
    error "missing option --freq. It's required with --vhost" -
    return $?
  elif [ -z "$vhost" -a -n "$freq" ]; then
    error "missing option --vhost. It's required with --freq" -
    return $?
  fi

  if [ -z "$vhost" ]; then
    cmd_args=( "$sys_dir/libexec/create-recurring-snapshots-starter" -Y )
  else
    cmd_args=( "$sys_dir/libexec/create-recurring-snapshot" "$vhost" "$freq" )
  fi

  "${cmd_args[@]}"
}
