#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} <s3_args>

  Options:
    None

  Auxiliary command to inspect S3. All arguments are passed directly to
  s3cmd.
"

devpanel_cmd__s3() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local host_base host_bucket region
  local -a cmd_args=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        break
        ;;
    esac
  done

  if ! hash s3cmd &>/dev/null; then
    error "command s3cmd is not installed." -
    return $?
  fi

  [ -z "$1" ] && usage

  if [ -z "$conf__s3__bucket_name" ]; then
    error "S3 integration is not configured" -
    return $?
  fi

  local s3cfg_file=/etc/devpanel/provisioners/aws/.s3cfg/default
  if [ ! -f "$s3cfg_file" ]; then
    error "missing configuration file $s3cfg_file" -
    return $?
  fi

  s3cmd -c "$s3cfg_file" "$@"
}
