#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --name <vhost>

  Options:
    --name <hostname>         the base hostname for virtual hosts

  Sets the base hostname for virtual hosts.
"

devpanel_cmd__set_base_hostname() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local arg name

  while [ -n "$1" ]; do
    arg="$1"
    case "$arg" in
      --name)
        [ -z "$2" ] && error_missing_value name
        name="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      --[A-Za-z0-9_-]*)
        error "unknown option $arg"
        ;;
      *)
        usage
        ;;
    esac
  done

  [ -z "$name" ] && error_missing_param name

  "$sys_dir/libexec/config-vhost-names-default" "$name"
}
