#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --version <version>

  Options:
    --version <version>     the the specified version
    --help                  display the command usage

  Sets the platform version to which this host will connect to.

"

devpanel_cmd__set_platform_version() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name version
  local -a cmd_args_ar=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --version)
        [ -z "$2" ] && error_missing_value "$name"
        if [[ "$2" =~ ^[1-9]$ ]]; then
          version="$2"
        else
          echo "$FUNCNAME(): invalid version string specified (must be [1-9])" 1>&2
          return 1
        fi

        shift 2
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      *)
        error "unknown option $name"
        ;;
    esac
  done

  [ -z "$version" ] && error_missing_param version

  if save_opts_in_devpanel_config "platform.version = $version"; then
    echo "Successfully set the platform version to $version."
  else
    echo "Failed to set platform version." 1>&2
    return 1
  fi

}
