#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action [opts] [--vhost <vhost>] [--domain <domain>]

  Options:
    --vhost  <vhost>         the vhost
    --domain <domain>        find the vhost associated with the
                             specified domain
    --conditional            only start if the vhost is not disabled and
                             if mysql was not intentionally stopped

  Starts mysqld associated with the specified domain or vhost.
"

devpanel_cmd__start_mysql() {
  local param vhost vhost_user db_user domain
  local conditional
  
  [ $# -eq 0 -o -z "$1" ] && usage

  while [ -n "$1" ]; do
    param="$1"

    case $param in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --domain)
        [ -z "$2" ] && error_missing_value domain
        domain="$2"
        shift 2
        ;;
      --conditional)
        conditional=1
        shift
        ;;
      --help)
        usage
        ;;
      --)
        shift
        break
        ;;
      *)
        error "unknown parameter: $param"
        ;;
    esac
  done

  if [ -z "$vhost" -a -z "$domain" ]; then
    error "either --vhost or --domain needs to be specified"
  fi

  if [ -z "$vhost" ]; then
    vhost=$(get_vhost_with_hostname "$domain")
    if [ $? -ne 0 ]; then
      error "didn't find any vhost with the specified hostname"
    fi
  fi

  load_vhost_config "$vhost" || return $?
  vhost_user="$v__vhost__linux_user"

  if [ -z "$v__mysql__instance" ]; then
    if [ -t 0 ]; then
      echo "Warning: this vhost doesn't have any mysql instance" 1>&2
    fi

    return 0
  fi

  db_user="b_${vhost_user#w_}"
     
  local action
  if [ -n "$conditional" ]; then
    if ! is_vhost_enabled "$vhost"; then
      # vhost is disabled, don't start it
      return 0
    fi

    action="cond-start"
  else
    action=start
  fi

  "$sys_dir/compat/dbmgr/current/bin/daemon-action" "$action" "$db_user"
}
