#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] --yes

  Options:
    --yes               confirm the intent to run

  Starts all mysql instances.
"

devpanel_cmd__start_mysql_instances() {
  local arg locked confirmed instance

  while [ -n "$1" ]; do
    arg="$1"
    case "$arg" in
      --yes)
        confirmed=yes
        shift
        ;;

      *)
        error "unknown option '$arg'" -
        shift
        return 1
        ;;
    esac
  done

  [ -z "$confirmed" ] && usage

  lock_file="$conf__paths__lock_dir/${BASH_SOURCE##*/}.lock"

  if ln -s $BASHPID "$lock_file" 2>/dev/null; then
    locked=1
    devpanel_trap_exit_cmds_ar+=( "rm -f $lock_file" )
  else
    if [ -t 0 ]; then
      echo "Warning: there's another instance running. Exiting." 1>&2
    fi

    return 1
  fi

  for instance in $(get_list_of_mysql_instances); do
    load_mysql_instance_config "$instance" || continue

    if ! is_var_set_to_yes mysql__params__enabled; then
      continue
    fi

    if has_a_safe_level_of_free_ram; then
      # if the database was not manually stopped by the user, then start it
      devpanel_run start mysql instance --instance "$instance" \
                      --conditional --quick
    else
      # not enough free ram, the server might be in a high memory pressure.
      # Just stop trying to start databases
      break
    fi
  done

  cleanup_namespace mysql

  return 0
}
