#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action [opts] <--vhost vhost | --domain domain.tld>

  Options:
    --vhost  <vhost>         the vhost
    --domain <domain>        find the vhost associated with the
                             specified domain

  Returns the status of the mysql instance of a vhost.
"

devpanel_cmd__status_mysql() {
  local param vhost vhost_user db_user domain instance
  
  [ $# -eq 0 -o -z "$1" ] && usage

  while [ -n "$1" ]; do
    param="$1"

    case $param in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --domain)
        [ -z "$2" ] && error_missing_value domain
        domain="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      --)
        shift
        break
        ;;
      *)
        error "unknown parameter: $param"
        ;;
    esac
  done

  if [ -z "$vhost" -a -z "$domain" ]; then
    error "either --vhost or --domain needs to be specified"
  fi

  if [ -n "$domain" ]; then
    vhost=$(get_vhost_with_hostname "$domain")
    if [ $? -ne 0 ]; then
      error "didn't find any vhost with the specified hostname"
    fi
  fi

  load_vhost_config "$vhost" || return $?
  if [ -n "$v__mysql__instance" ]; then
    instance="$v__mysql__instance"
  else
    error "this vhost doesn't have any mysql instance" -
    return $?
  fi

  mysql_ping_instance "$instance"
}
