#!/bin/bash

set_usage_msg \
  "Usage: $bin_name $action [opts] [--vhost <vhost>] [--domain <domain>]

  Options:
    --vhost  <vhost>         the vhost
    --domain <domain>        find the vhost associated with the
                             specified domain

  Stops mysqld associated with the specified domain or vhost.
"

devpanel_cmd__stop_mysql() {
  local param vhost vhost_user db_user domain
  
  [ $# -eq 0 -o -z "$1" ] && usage

  while [ -n "$1" ]; do
    param="$1"

    case $param in
      --vhost)
        [ -z "$2" ] && error_missing_value vhost
        vhost="$2"
        shift 2
        ;;
      --domain)
        [ -z "$2" ] && error_missing_value domain
        domain="$2"
        shift 2
        ;;
      --help)
        usage
        ;;
      --)
        shift
        break
        ;;
      *)
        error "unknown parameter: $param"
        ;;
    esac
  done

  if [ -z "$vhost" -a -z "$domain" ]; then
    error "either --vhost or --domain needs to be specified"
  fi

  if [ -z "$vhost" ]; then
    vhost=$(get_vhost_with_hostname "$domain")
    if [ $? -ne 0 ]; then
      error "didn't find any vhost with the specified hostname"
    fi
  fi

  load_vhost_config "$vhost" || return $?
  vhost_user="$v__vhost__linux_user"

  db_user="b_${vhost_user#w_}"
     
  "$sys_dir/compat/dbmgr/current/bin/daemon-action" stop "$db_user"
  if [ $? -eq 0 ]; then
    echo "Successfully stopped mysql instance for vhost $vhost"
  else
    error "unable to stop mysql instance for vhost $vhost"
  fi
}
