#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts] <--instance|--vhost> <name>

  Options:
    --instance <name>       name of the mysql instance
    --vhost <vhost>         use the mysql instance related to the vhost
    --once                  show the lines once, don't follow the log
                            changes (i.e. tail without -f)

  Tails the MySQL log file for the specified mysql instance. Either
  --instance or --vhost need to be specified.
"

devpanel_cmd__tail_mysql_log() {
  [ $# -eq 0 -o -z "$1" ] && usage

  local name vhost instance show_once
  local -a tail_args_ar=()

  while [ -n "$1" ]; do
    name="$1"
    case "$name" in
      --vhost)
        [ -z "$2" ] && { error_missing_value "$name" ; return $?; }
        vhost="$2"
        shift 2
        ;;

      --instance)
        [ -z "$2" ] && { error_missing_value "$name" ; return $?; }
        instance="$2"
        shift 2
        ;;

      --help)
        usage
        ;;

      --)
        shift
        break
        ;;

      --once)
        show_once=1
        shift
        ;;

      *)
        error "unknown option $name" - 
				return $?
        ;;
    esac
  done

  if [ -n "$instance" -a -n "$vhost" ]; then
    error "can't use both --instance and --vhost on the same command" -
    return $?
  elif [ -z "$instance" -a -z "$vhost" ]; then
    usage
  fi

  if [ -n "$vhost" ]; then
    load_vhost_config "$vhost" || return $?

    if [ -n "$v__mysql__instance" ]; then
      instance="$v__mysql__instance"
    else
      error "this vhost is not associated to any mysql instance." -
      return $?
    fi
  fi

  load_mysql_instance_config "$instance" || return $?

  local log_file db_user

  db_user="$mysql__params__linux_user"
  if ! linuxuser_exists "$db_user"; then
    error "user '$db_user' doesn't exist." -
    return $?
  fi

  log_file=$(eval echo -n ~$db_user/mysql/error.log)
  if [ ! -f "$log_file" ]; then
    error "missing log file $log_file" -
    return $?
  fi

  if [ -z "$show_once" ]; then
    tail_args_ar+=( -f )
  fi

  tail "${tail_args_ar[@]}" "$log_file"
}
