#!/bin/bash

set_usage_msg \
  "Usage: $bin_name ${cmd_ar[*]} [opts]

  Updates the local devPanel installation.
"

devpanel_cmd__update() {
  # first update the system scripts
  "$sys_dir/libexec/update-scripts" || return $?

  # then update the system packages
  "$sys_dir/libexec/package-mgr" update-all -y
}
