#!/bin/bash

usage() {
  echo "Usage: `basename "$0"` <vhost> <domain_list>

domain_list is comma separated domain names

"
  exit 1
}

# main

[ $# -lt 2 ] && usage

self=`readlink -e "$0"`
dir=`dirname "$self"`
we_base_dir=`readlink -e "$dir/../.."`

lib_file="$we_base_dir/lib/functions"
if ! source "$lib_file"; then
  echo "Error: unable to source lib file '$lib_file'" 1>&2
  exit 1
fi

vhost="$1"
domain_list="$2"

webserver_ips=`"$dir/get-cluster-webserver-ips"`
if [ $? -ne 0 ]; then
  echo "Error: unable to get IPs of webservers" 1>&2
  exit 1
fi

for ip in "$webserver_ips"; do
  ssh root@"$ip" /opt/webenabled/paas-provisioner/aws/config-vhost \
    "$vhost" "$domain_list"
done

exit 0
