#!/bin/bash

# main

self_bin=`readlink -e "$0"`
curr_dir=`dirname "$self_bin"`
we_base_dir=`readlink -e "$curr_dir/../.."`
lib_file="$we_base_dir/lib/functions"

if ! source "$lib_file"; then
  echo "Error: unable to source lib file $lib_file" 1>&2
  exit 1
fi

region=$(get_aws_cluster_region ) || exit $?
stack_name=$(get_aws_cluster_stack_id ) || exit $?

tmp_file=`mktemp`
if [ $? -ne 0 ]; then
  echo "Error: unable to create temporary file" 1>&2
  exit 1
fi
trap 'rm -f -- "$tmp_file"' EXIT

self_bin=`readlink -e "${BASH_SOURCE[0]}"`
curr_dir=`dirname "$self_bin"`
base_dir=`readlink -e "$curr_dir"`
info_bin="$base_dir/get-aws-json-property"

hash -p "$info_bin" aws_get_info

aws ec2 describe-instances --region "$region" \
  --filters "Name=tag:aws:cloudformation:stack-name,Values=$stack_name" \
  "Name=tag:aws:cloudformation:logical-id,Values=WebServerGroup" >"$tmp_file"

if [ $? -ne 0 ]; then
  echo "Error: unable to get list of running instances" >&2
  exit 1
fi

aws_get_info get-webservers-ipv4 "$tmp_file"
if [ $? -ne 0 ]; then
  echo "Error: unable to get list of IPs" >&2
  exit 1
fi

exit 0
