#!/bin/bash

settings_file="/var/www/html/sites/default/settings.php"

if [ ! -f "$settings_file" ]; then
  exit 0
fi

self_bin=`readlink -e "$0"`
curr_dir=`dirname "$self_bin"`
base_dir=`readlink -e "$curr_dir/../.."`

source "$base_dir/lib/functions"

ini_file="$base_dir/etc/aws-cluster.ini"

rds_db=`ini_section_get_key_value "$ini_file" client database`
rds_host=`ini_section_get_key_value "$ini_file" client host`
rds_port=`ini_section_get_key_value "$ini_file" client port`
rds_user=`ini_section_get_key_value "$ini_file" client user`
rds_pw=`ini_section_get_key_value "$ini_file" client password`
rds_pw_esc=`escape_sed "$rds_pw"`

sed -i -e "
  s/^\([[:space:]]*[\"']database[\"'][[:space:]]*\)=>.\+/\1 => '$rds_db',/;
  s/^\([[:space:]]*[\"']host[\"'][[:space:]]*\)=>.\+/\1 => '$rds_host',/;
  s/^\([[:space:]]*[\"']port[\"'][[:space:]]*\)=>.\+/\1 => '$rds_port',/;
  s/^\([[:space:]]*[\"']username[\"'][[:space:]]*\)=>.\+/\1 => '$rds_user',/;
  s/^\([[:space:]]*[\"']password[\"'][[:space:]]*\)=>.\+/\1 => '$rds_pw_esc',/;
" "$settings_file"
