#!/bin/bash

usage() {
  echo "Usage: `basename "$0"` <vhost>"
  exit 1
}

# main
[ -z "$1" ] && usage

vhost="$1"
settings_file="/var/www/html/$vhost/sites/default/settings.php"

if [ ! -f "$settings_file" ]; then
  exit 0
fi

self_bin=`readlink -e "$0"`
curr_dir=`dirname "$self_bin"`
base_dir=`readlink -e "$curr_dir/../.."`

source "$base_dir/lib/functions"

ini_file="$base_dir/etc/aws-rds--my_cnf-$vhost.ini"

rds_db=`ini_section_get_key_value "$ini_file" client database`
rds_host=`ini_section_get_key_value "$ini_file" client host`
rds_port=`ini_section_get_key_value "$ini_file" client port`
rds_user=`ini_section_get_key_value "$ini_file" client user`
rds_pw=`ini_section_get_key_value "$ini_file" client password`
rds_pw_esc=`escape_sed "$rds_pw"`

sed -i -e "
  s/^\([[:space:]]*[\"']database[\"'][[:space:]]*\)=>.\+/\1 => '$rds_db',/;
  s/^\([[:space:]]*[\"']host[\"'][[:space:]]*\)=>.\+/\1 => '$rds_host',/;
  s/^\([[:space:]]*[\"']port[\"'][[:space:]]*\)=>.\+/\1 => '$rds_port',/;
  s/^\([[:space:]]*[\"']username[\"'][[:space:]]*\)=>.\+/\1 => '$rds_user',/;
  s/^\([[:space:]]*[\"']password[\"'][[:space:]]*\)=>.\+/\1 => '$rds_pw_esc',/;
" "$settings_file"

site_title="`mysql --defaults-file="$ini_file" -BN -D "$rds_db" -e "select value from variable where name='site_name'"`"
if [ -n "$site_title" ] && ! [[ "$site_title" =~ Cluster ]]; then
  site_title_esc="$site_title"
  site_title_esc="${site_title_esc#s:*:\"}"
  site_title_esc="${site_title_esc%\"}"
  site_title_esc="$site_title_esc - Cluster"

  sql_upd_site_title="`printf "UPDATE variable SET value = 's:%s:\\\"%s\\\"' WHERE name = 'site_name';" ${#site_title_esc} "$site_title_esc";`"
  mysql --defaults-file="$ini_file" -BN -D "$rds_db" \
    -e "$sql_upd_site_title"
fi
