#!/bin/bash

self_bin=$(readlink -e "${BASH_SOURCE[0]}")
self_dir=${self_bin%/*}
sys_dir=${self_dir%/*}

lib_f="$sys_dir/lib/functions"
if ! source "$lib_f"; then
  echo "Error: unable to import $lib_f" 1>&2
  exit 1
fi

public_html_dir=$(get_docroot_from_vhost "$DEVPANEL_VHOST")
if [ -d "$public_html_dir" ]; then
  cd "$public_html_dir"
fi

: just return 0
