#!/bin/bash

self_bin=$(readlink -e "${BASH_SOURCE[0]}")
self_dir=${self_bin%/*}
sys_dir=${self_dir%/*}

lib_f="$sys_dir/lib/functions"
if ! source "$lib_f"; then
  echo "Error: unable to import $lib_f" 1>&2
  exit 1
fi

. /etc/profile

load_devpanel_config

vhost=$(get_vhost_from_linuxuser)
if [ $? -eq 0 ]; then
  if load_vhost_config "$vhost"; then
    public_html_dir="$v__vhost__document_root"
    if [ -d "$public_html_dir" ]; then
      cd "$public_html_dir"
    fi
  fi
else
  # unable to get public_html dir. Just chdir into the user directory
  cd
fi

: just return 0
