#!/bin/sh
# multi-server version
# Usage:
#   restore-vhost-multiserver [OPTIONS] target_vhost source_vhost label [fqdn ...]
# Options:
#   -P replicate w_* user's password
#   -i pass mysql passwd via stdin

dir=`dirname "$0"`
options=""
opt_i=0

while getopts "Pi" OPTOPT
do
  case "$OPTOPT" in
    P) options="${options+ }-P";;
    i) opt_i=1; target_options="${target_options+ }-i";;
    *) exit 1;
  esac
done
shift `expr $OPTIND - 1`

source_server=localhost
target_server=localhost
[ -n "$WEBENABLED_SERVER" ] && source_server=$WEBENABLED_SERVER
[ -n "$WEBENABLED_SERVER" ] && target_server=$WEBENABLED_SERVER
[ -n "$WEBENABLED_SOURCE_SERVER" ] && source_server=$WEBENABLED_SOURCE_SERVER
[ -n "$WEBENABLED_TARGET_SERVER" ] && target_server=$WEBENABLED_TARGET_SERVER
unset WEBENABLED_SERVER

error()
{
  echo "ERROR${1+: }$@" >&2
  exit 1
}

usage()
{
  echo "Usage: restore-vhost-multiserver [OPTIONS] TARGET_VHOST SOURCE_VHOST LABEL [FQDN ...]" >&2
  exit 1
}
# JCD this line causes failure even though the args are correct in some cases [ $# = 3 ] || usage
target="$1"
source="$2"
label="$3"
shift 3

if ! TMPFILE="`mktemp -t restore_vhost-multiserver.XXXXXXXXXX`"
then
  echo "ERROR: mktemp failed";
  exit 1
fi

trap 'echo "Removing temporary archive $TMPFILE"; rm -f -- "$TMPFILE"' \
  EXIT HUP INT QUIT ILL TRAP ABRT BUS FPE KILL SEGV PIPE STOP ALRM TERM

if [ $opt_i = 1 ]
then
  read -r password || error "Cannot read password"
  [ -n "$password" ] || error "Empty password"
  echo "$password" >$TMPFILE || error
fi

echo "Restore stage 1: archive $source $label to $TMPFILE"
if ! WEBENABLED_SERVER="$source_server" $dir/archive-vhost-transfer "$source" "$label" >>"$TMPFILE"
then
  echo ERROR >&2
  exit 1
fi
  
echo "Restore stage 2: restore $target from $TMPFILE"
WEBENABLED_SERVER="$target_server" $dir/restore-vhost $options $target_options "$target" - "$@" <"$TMPFILE" || error
echo Done
