#!/bin/sh
if ! [ -d /opt/webenabled/config/os.owl/pathnames/etc/ssl ]
then
  echo Creating /opt/webenabled/config/os.owl/pathnames/etc/ssl
  mkdir /opt/webenabled/config/os.owl/pathnames/etc/ssl
  chmod 755 /opt/webenabled/config/os.owl/pathnames/etc/ssl
  ln -s /etc/ssl/certs /opt/webenabled/config/os.owl/pathnames/etc/ssl
  ln -s /etc/ssl/keys /opt/webenabled/config/os.owl/pathnames/etc/ssl
fi

# FIXME: Add a step for cloud9 (see the WARNING for 2011-04-05-grg in ChangeLog)
