#!/bin/bash

usage() {
  local prog=`basename "$0"`

  echo "Usage: $prog [ options ] <vhost>
  
  For the [ options ] see ../bin/metadata-handler usage.

"

  exit 1
}

error() {
  local msg="$1"
  local exit_code="${2:-1}"

  [ -n "$msg" ] && echo "Error: $msg" 1>&2
  exit $exit_code
}

# main

[ $# -eq 0 ] && usage

if [ $EUID -ne 0 ]; then
  error "this command requires ROOT privileges to be run."
fi

getopt_flags='nq'
target_opts=''
while getopts $getopt_flags OPTN; do
  case $OPTN in
    [nq])
      target_opts+=" -$OPTN"
      ;;
    *)
      usage
      ;;
  esac
done
[ $OPTIND -gt 1 ] && shift $(( $OPTIND - 1 ))

[ -z "$1" ] && usage

vhost=`basename "$1"`

curr_dir=`dirname "$0"`
base_dir=`readlink -e "$curr_dir/.."`
bin_file="$base_dir/bin/metadata-handler"
if [ $? -ne 0 -o -z "$bin_file" ]; then
  error "couldn't find metadata-handler executable"
fi

vhost_dir="$base_dir/config/vhosts/$vhost"
if [ ! -e "$vhost_dir" ]; then
  error "vhost dir '$vhost_dir' doesn't exist."
elif [ ! -d "$vhost_dir" ]; then
  error "path '$vhost_dir' is not a directory."
fi

"$bin_file" ${target_opts:+ $target_opts} "$vhost_dir"
