#!/bin/bash

opt_P=0

while getopts "P" OPTOPT
do
  case "$OPTOPT" in
    P) opt_P=1;;
    *) exit 1;
  esac
done
shift `expr $OPTIND - 1`

run()
{
  echo "  running $@"
  "$@"
}
run_su()
{
  echo "  running su -l -c '$@' $user" >&2
  su -l -c "$*" "$user"
}


dir=`dirname $0`
vhost="$1"
archive_dir="$2"
user="w_$vhost"
home="`eval \"echo ~$user\"`"
date=`date  +'%Y%m%d'`
archive_file="$archive_dir/$user.tgz"
conf="$dir/../config/os/pathnames/etc/apache_vhosts/$user.conf"
archive_shadow="$archive_dir/$user.shadow"
archive_conf="$archive_dir/apache_$vhost.conf"
logs_dir="$dir/../config/os/pathnames/var/log/apache_vhosts/$user"
archive_logs="$archive_dir/logs_$vhost.tgz"
archive_id="$archive_dir/id"
archive_crontab="$archive_dir/crontab"

if ! `id -u "$user" 2>/dev/null >/dev/null`
then
  echo "No such user: $user" >&2
  exit 1
fi

if ! [ -d "$home" ]
then
  echo "Home dir $home does not exist" >&2
  exit 1
fi

if ! [ -d "$logs_dir" ]
then
  echo "Logdir $logs_dir does not exist" >&2
  exit 1
fi

abort_if_exists()
{
  local file="$1"
  if [ -r "$file" ]
  then
    echo "$file must not exist" >&2
    exit 1
  fi
}

create_file()
{
  local file="$1"
  set -C
  echo -n >"$file"
  local status=$?
  set +C
  return $status
}

echo "Locking $archive_dir..."
run mkdir -p "$archive_dir" || exit 1
if ! create_file "$archive_id" 2>/dev/null
then
  echo "$archive_id must not exist" >&2
  exit 1
fi

if ! chmod +w "$archive_id"; then
  echo "Error: unable to make file '$archive_id' writable." 1>&2
  exit 1
fi

abort_if_exists "$archive_file"
abort_if_exists "$archive_logs"
abort_if_exists "$archive_conf"


echo "Archiving $home to $archive_file"
echo "$vhost" >$archive_id
if ! run tar --exclude ./public_html/gen/archive --exclude ./logs \
 -C "$home" -zcf "$archive_file" .; then
  echo "Error: unable to archive the site files" 1>&2
  exit 1
fi

echo "Copying apache config to $archive_conf"
if ! cp "$conf" "$archive_conf"; then
  echo "Error: unable to copy apache file '$conf' to '$archive_conf'" 1>&2
  exit 1
fi

echo "Archiving $logs_dir to $archive_logs"
if ! run mkdir -p "$archive_dir"; then
  echo "Error: unable to create dir '$archive_dir'" 1>&2
  exit 1
fi

if ! run tar --ignore-failed-read -C "$logs_dir" -zcf "$archive_logs" .; then
  echo "Warning: unable to archive the log files..." 1>&2
fi

echo "Archiving crontab to $archive_crontab"
if crontab_contents=`run_su crontab -l` 2>&1; then
  echo "$crontab_contents" | sed '/^#/{1d;2d;3d}' |run tee "$archive_crontab"
  if [ $? -ne 0 ]; then
    echo "Error: unable to archive crontab contents" 1>&2
    exit 1
  fi
else
  touch "$archive_crontab"
fi

if [ $opt_P = 1 ]; then
  echo "Saving shadow to $archive_shadow"
  if ! getent shadow "$user" >"$archive_shadow"; then
    echo "Error: unable to archive shadow file for user '$user'" 1>&2
    exit 1
  fi
fi

