#!/bin/bash
dir=`dirname $0`
dir_bin="$dir/../bin"
vhost="$1"
label="$2"
error()
{
  echo "ERROR${1+: }$@" >&2
  exit 1
}
case "$0" in
  *-list) action=list;;
  *-transfer) action=transfer;;
  *) error "invalid action";;
esac
# using mode archive: it's OK to operate on a locked vhost
$dir/check-vhost-name archive "$vhost" || exit 1
home="`eval \"echo ~$user\"`" || error
[ -d "$home" ] || error "Home dir $home does not exist"

lib_f="$dir/../lib/functions"
if ! source "$lib_f"; then
  echo "Error: unable to import $lib_f" 1>&2
  exit 1
fi

get_linux_username_from_vhost "$vhost" && \
user="$_dp_value"
if [ $? -ne 0 ]; then
  error "unable to get the linux username from vhost $vhost"
fi


if [ -n "$label" ]; then $dir/check-archive-pathname -u"$vhost" restore "$home/public_html/gen/archive/$label" || exit 1; fi
echo -n "$label"|su -l -c "$dir_bin/archive-vhost-action $action" "$user"
