#!/bin/bash

usage() {
  echo "Usage: `basename "$0"` [ options ] <vhost> <archive_dir>

  Options:
    -n            don't lock DB tables when dumping
    -e            accept the use of an existing non-empty archive_dir


Archives all databases from vhost into the archive dir.
"
  exit 1
}

dir_empty()
{
  local dir="$1"
  [ -d "$dir" ] || return 0
  set -- $dir/.??* $dir/.[!.] $dir/*
  case $#$* in
    "3$dir/.??* $dir/.[!.] $dir/*")
      return 0;;
    *)
      return 1;;
  esac
}



run()
{
  echo "  running $@"
  "$@"
}
run2()
{
  echo "  running $@" >&2
  "$@"
}

run_su()
{
  echo "  running su -s /bin/sh -l -c '$@' $user" >&2
  su -s /bin/bash -l -c "$*" "$user"
}

create_file()
{
  local file="$1"
  set -C
  echo -n >"$file"
  local status=$?
  set +C
  return $status
}


# main
[ $# -lt 2 ] && usage

unset dont_lock_tables use_existing_dir lock_cmd_arg db_prefix
getopt_flags='ne'
while getopts $getopt_flags OPTN; do
  case $OPTN in
    n)
      dont_lock_tables=1
      ;;
    e)
      use_existing_dir=1
      ;;
    L)
      unset dont_lock_tables
      lock_cmd_arg=1
      ;;
    *)
      exit 1
      ;;
  esac
done
[ $OPTIND -gt 0 ] && shift $(( $OPTIND - 1 ))

vhost="$1"
archive_dir="$2"
if [ -z "$vhost" -o -z "$archive_dir" ]; then
  usage
fi

self_bin=$(readlink -e "$0")
dir=`dirname "$self_bin"`
sys_dir=$(readlink -e "$dir/..")

lib_file="$sys_dir/lib/functions"
if ! source "$lib_file"; then
  echo "Error: unable to load lib file $lib_file" 1>&2
  exit 1
fi
load_devpanel_config || exit $?

load_vhost_config "$vhost" || exit $?

if [ -z "$v__mysql__instance" ]; then
  echo "Warning: this vhost is not associated to any mysql instance" 1>&2
  exit 1
fi

if [ -n "$v__mysql__database_prefix" ]; then
  db_prefix="$v__mysql__database_prefix"
fi

instance_ini="$lamp__paths__mysql_instances_config_dir/$v__mysql__instance/config.ini"
read_ini_file_into_namespace --no-cleanup "$instance_ini" v__mysql || exit $?

user_web="$v__vhost__linux_user"
user="$v__mysql__params__linux_user"
tmp_db_list="$archive_dir/tmp_databases"
archive_list="$archive_dir/databases"
archive_my_cnf="$archive_dir/b_.my.cnf"
home="$v__vhost__linux_user_home"
date=`date  +'%Y%m%d'`

#if ! `id -u "$user" 2>/dev/null >/dev/null`
#then
#  echo "No such user: $user" >&2
#  exit 1
#fi

if ! [ -d "$home" ]
then
  echo "Home dir $home does not exist" >&2
  exit 1
fi

if [ -z "$use_existing_dir" ] && ! dir_empty "$archive_dir"
then
  echo "Target directory is not empty: $archive_dir" >&2
  exit 1
elif [ -n "$use_existing_dir" -a ! -e "$archive_dir" ]; then
  echo "Error: path '$archive_dir' doesn't exist" 1>&2
  exit 1
elif [ -n "$use_existing_dir" -a ! -d "$archive_dir" ]; then
  echo "Error: path '$archive_dir' is not a directory" 1>&2
  exit 1
elif [ -z "$use_existing_dir" ]; then
  echo "Locking $archive_dir..."
  if ! run mkdir -p "$archive_dir"; then
    echo "Error: unable to create dir '$archive_dir'" 1>&2
    exit 1
  fi
fi

if ! create_file "$archive_list" 2>/dev/null
then
  echo "$archive_list must not exist" >&2
  exit 1
fi

echo Listing the databases...
if is_var_set_to_yes v__mysql__external; then
  mysql_list_databases_as_vhost "$vhost" >$tmp_db_list
  st=$?
else
  mysql_list_databases "$v__mysql__instance" >$tmp_db_list
  st=$?
fi
if [ $st -eq 0 ]; then
  sed -i -e '/^mysql$/d; /^performance_schema$/d; /^information_schema$/d;
              /^sys$/d;' "$tmp_db_list"
else
  error "unable to list mysql databases"
fi

echo Checking for .my.cnf...
if run_su "[ -s .my.cnf ]"
then
  echo Found, saving .my.cnf...
  if ! run_su "cat .my.cnf" >"$archive_my_cnf"
  then
     echo "Aborting" >&2
     exit 1
  fi
else 
  echo Not found
fi

if [ -s "$tmp_db_list" ]; then
  while read database; do
    if [ -n "$db_prefix" ]; then
      final_db_name="${database#$db_prefix}"
    else
      final_db_name="$database"
    fi
    archive_file="$archive_dir/$final_db_name.sql"

    echo "Archiving $database to $archive_file"
    if mysql_dump_database "$v__mysql__instance" "$database" >$archive_file; then
      if ! gzip "$archive_file"; then
        error "failed to gzip database file '$archive_file'"
      fi
      echo "$final_db_name" >>$archive_list
    else
      error "failed to dump database '$database'"
    fi
  done < "$tmp_db_list"

  rm -f "$tmp_db_list"
fi

exit 0
