#!/bin/bash
usage(){
  local self=${0##*/}

echo "
Enables or disables running regular updates of Linux distribution packages.

Keep in mind that some programs may break due to unexpected updates or changes in the libraries
Use this at your own risk.

Usage: $self <on|off>
"
  exit 1
}

# Turn on Updates doing some validations for ubuntu and centos or rhel based distributions
autoupdatesOn(){
  echo "set automatic_distro_updates 1" | "$sys_dir/libexec/system-metadata-handler" -q
  if [ $? -eq 0 ]; then
    echo "Automatic updates ON"
    return 0
  else
    echo "Error: unable to enabled auto updates" 1>&2
    return 1
  fi
}

autoupdatesOff(){
  echo "rm automatic_distro_updates" | "$sys_dir/libexec/system-metadata-handler" -q
  if [ $? -eq 0 ]; then
    echo "Automatic updates OFF"
    return 0
  else
    echo "Error: failed to disable auto updates" 1>&2
    return 1
  fi
}

# main

[ -z "$1" ] && usage

self_bin=$(readlink -e "$0")
if [ $? -ne 0 ]; then
  echo "Error: unable to detect self path" 1>&2
  exit 1
fi
self_dir=${self_bin%/*}
sys_dir=${self_dir%/*}
lib_file="$sys_dir/lib/functions"

if ! source "$lib_file"; then
  echo "Error: unable to source file $lib_file"
  exit 1
fi

case  $1  in
        on)       
                autoupdatesOn
                exit $?
                ;;
        off)
                autoupdatesOff
                exit $?
                ;;            
        h|help)       
                usage
                ;;
        *)
                usage              
esac
