#!/bin/bash

usage(){
echo "This script is used to install a defined PHP version on the user specified"
echo "Example: ./config-php <PHPversion> <User>"
echo "Usage: ./config-php 5.5.5 w_user"
}
#######distro
DIS="apache2"
CONF="apache2.conf"
if [  -d "/etc/httpd" ]; then  
	DIS=httpd
	CONF="$(find /etc/httpd/ -iname 'httpd.conf' )"

fi 

###################         /home/clients/websites/w_supert
PHPVERSION=$1
PHPUSER=$2
BASEPATH="/home/clients/websites/$PHPUSER/php"

#echo "Installing version $PHPVERSION on $BASEPATH"
# Create php directory and copy to temp in case the directory exists
if [ ! -d "$BASEPATH" ]; then
	echo "Creating $BASEPATH ..."
	su -c "mkdir -p $BASEPATH" -s /bin/bash $PHPUSER
else
	echo "$BASEPATH exists, updating PHP version to $PHPVERSION"
	echo "Copying $BASEPATH to tmp ..."
	rm -rf /tmp/php
	mv  $BASEPATH /tmp
	su -c "mkdir -p $BASEPATH" -s /bin/bash $PHPUSER
fi

cd $BASEPATH
#####DOWNLOAD DE PHP  
#su -c "cp -R /opt/webenabled/bin/packages/php/$PHPVERSION/* . " -s /bin/bash $PHPUSER
su -c "wget https://updates.devpanel.com/php/$PHPVERSION\.$DIS\.tar.gz" -s /bin/bash $PHPUSER
su -c "tar -zxf $PHPVERSION\.$DIS\.tar.gz" -s /bin/bash $PHPUSER
su -c "mv $PHPVERSION/* . &&  rm -rf $PHPVERSION " -s /bin/bash $PHPUSER
echo "#! /bin/bash 
PHP_FCGI_MAX_REQUESTS=10000 
export PHP_FCGI_MAX_REQUESTS  
exec $BASEPATH/bin/php-cgi"> $BASEPATH/bin/fcgiwrapper.cgi



#### modificar vhost. 
FCGI=" <IfModule mod_fcgid.c>\n                AddHandler fcgid-script .php\n               FCGIWrapper $BASEPATH/bin/fcgiwrapper.cgi\n        </IfModule>\n    "
###INSERT IS A NEW INSTALATION 
####if as a update should not have any problem because the path of php is the same :) 
if ( ! grep -q "FCGIWrapper $BASEPATH/bin/fcgiwrapper.cgi" /etc/$DIS/devpanel-virtwww/$PHPUSER\.conf) ; then
touch /etc/$DIS/devpanel-virtwww/$PHPUSER\.conf2
sed "/SuexecUserGroup $PHPUSER virtwww/a $FCGI "  /etc/$DIS/devpanel-virtwww/$PHPUSER\.conf > /etc/$DIS/devpanel-virtwww/$PHPUSER\.conf2
cat /etc/$DIS/devpanel-virtwww/$PHPUSER\.conf2 > /etc/$DIS/devpanel-virtwww/$PHPUSER\.conf

#rm /etc/$DIS/devpanel-virtwww/$PHPUSER\.conf2
fi

######change owner just in case 
chown -R $PHPUSER:virtwww  $BASEPATH

#if [ ! -d "/tmp/php" ]; then 
#	if 
#
#fi

service apache2 reload
