#!/bin/bash
prefix=${WEBENABLED_DATA_DIR:-/opt/webenabled/data}

run()
{
  echo "  Running $@"
  "$@"
}

error()
{
  echo "ERROR${1+: }$@" >&2
  exit 1
}

usage()
{
  echo "Usage: clone-vhost SOURCE_VHOST TARGET_VHOST" >&2
  exit 1
}

# main
[ $# -lt 2 ] && usage
dir=`dirname "${BASH_SOURCE[0]}"`

[ -z "$1" -o -z "$2" ] && usage

while getopts "PpinS:I" OPTOPT
do
  case "$OPTOPT" in
    P) options="${options+ }-P";;
    p) target_options="$target_options${target_options+ }-p";;
    i) opt_i=1; target_options="$target_options${target_options+ }-i";;
    I) opt_I=1;;
    n) opt_n=1; target_options="$target_options${target_options+ }-n";;
    S) opt_S="$OPTARG";;
    *) exit 1;
  esac
done
shift `expr $OPTIND - 1`

source="$1"
target="$2"
shift
shift

$dir/check-vhost-name archive "$source" || usage
$dir/check-vhost-name restore "$target" || usage

TMP_FILE=`mktemp "$prefix/tmp_archive_$source.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"`.tgz

echo "Cloning stage 1: archive $source to $TMP_FILE"
if ! $dir/archive-vhost "$source" "$TMP_FILE"
then
  echo ERROR >&2
  exit 1
fi
  
echo "Cloning stage 2: restore $target from $TMP_FILE"
$dir/restore-vhost $target_options "$target" "$TMP_FILE" || error
echo "Cloning stage 3: removing archive from $TMP_FILE"
rm -f "$TMP_FILE"
echo Done
