#!/bin/bash
dir=`dirname $0`
dir_bin="$dir/../bin"
vhost="$1"
tar_command="$2"
param="$3"
user="w_$vhost"

# using mode archive: it's OK to operate on a locked vhost
$dir/check-vhost-name archive "$vhost" || exit 1

su -l -c "tar $param $tar_command" $user
exit 0

