#!/bin/bash
identity_dir=/opt/webenabled/config/ssh
authorized_keys=~r_we/.ssh/authorized_keys
weadmin_group=weadmin
tmp=`mktemp "$authorized_keys.XXXXXX"` || exit 1
trap 'rm -f "$tmp"' HUP INT QUIT ILL TRAP ABRT BUS FPE KILL SEGV PIPE STOP ALRM TERM
if [ -r "$authorized_keys" ]; then
  chmod --reference="$authorized_keys" "$tmp" || exit 1
  cat "$authorized_keys" >>"$tmp" || exit 1; 
fi
n=0
for type in local
do
  identity="$identity_dir/$type"
  if [ -r "$identity" ]
  then
    [ $type = local ] && echo "The $type key is already there"
    continue
  else
    [ $type = global ] && echo "WARNING: generating a global key"
  fi
  if ssh-keygen -P '' -t rsa -b 2048 -f "$identity" -C "$type webenabled administration" </dev/null
  then
    [ $type = local ] && echo -n 'from="127.0.0.1",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ' >>"$tmp" || exit 1
    cat "$identity.pub" >>"$tmp" || exit 1
  else
    exit 1
  fi
  n=`expr $n + 1`
done
if [ $n = 0 ]
then
  echo "Nothing to do" >&2
  exit 1
else
  mv "$tmp" "$authorized_keys" || exit 1
fi
