#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

usage(){
local self=${0##*/}
echo "This script will be used to install shell-in-a-box, this is used to have a web-based Terminal
Usage:
        $self <on/off>
"
}

# Call functions script to import detect_os method
self_bin=$(readlink -e "$0")
self_dir=${self_bin%/*}
sys_dir=${self_dir%/*}
lib_file="$sys_dir/lib/functions"

if ! source "$lib_file"; then
  echo "Error: unable to source file $lib_file"
  exit 1
fi

SHELLVHOST="/opt/webenabled/compat/apache_include/global-includes/shellinabox.conf"
installshell(){
local DEVPANELOS=$(devpanel_auto_detect_distro)
local SHELLDOMAIN="shell.$(hostname)"
# Only run it if we can (ie. on Ubuntu/Debian)
if [ "$DEVPANELOS" == "ubuntu" ] || [ "$DEVPANELOS" == "debian" ];then
        apt-get install -y --force-yes openssl shellinabox
echo "
SHELLINABOX_DAEMON_START=1
SHELLINABOX_PORT=4200
SHELLINABOX_ARGS=\"--no-beep --service=/:SSH --localhost-only --disable-ssl\"
" > /etc/default/shellinabox
        /etc/init.d/shellinabox restart
# Stop apache to install SSL
        assign_deref_os_fs_path_ex_or_exit apachectl "$sys_dir" pathnames/sbin/apachectl
        ## VALIDATION TO CHECK IF APACHE HAS GOOD CONFIGURATIONS
        #
        #
        #
        $apachectl stop
        git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt
        /opt/letsencrypt/letsencrypt-auto certonly --renew-by-default --email email@devpanel.com --text --agree-tos --standalone -d $SHELLDOMAIN

##Create Vhost
echo "Creating Shell vhost"
echo "
#Listen 443
<VirtualHost *:443>
    ServerName $SHELLDOMAIN
    SSLEngine On

    SSLCertificateFile /etc/letsencrypt/live/$SHELLDOMAIN/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/$SHELLDOMAIN/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/$SHELLDOMAIN/chain.pem

    ProxyPass / http://localhost:4200/
    ProxyPassReverse / http://localhost:4200/

</VirtualHost>
" > $SHELLVHOST
        $apachectl start

# Only run it if we can (ie. on RHEL/CentOS)
elif [ "$DEVPANELOS" == "centos" ] || [ "$DEVPANELOS" == "redhat" ];then
        yum -y install shellinabox
#echo "
#SHELLINABOX_DAEMON_START=1
#SHELLINABOX_PORT=4200
#SHELLINABOX_ARGS=\"--no-beep --service=/:SSH --localhost-only --disable-ssl\"
#" > /etc/sysconfig/shellinaboxd
        /etc/init.d/shellinaboxd restart
        git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt
        /opt/letsencrypt/letsencrypt-auto certonly --renew-by-default --email email@devpanel.com --text --agree-tos --standalone -d shell.$(hostname)
##### INITIATE SERVICE WHEN SYSTEM STARTS

else
  echo "unsupported OS"
  exit 1
fi
}

removeshell(){
DEVPANELOS=$(devpanel_auto_detect_distro)

# Only run it if we can (ie. on Ubuntu/Debian)
if [ "$DEVPANELOS" == "ubuntu" ] || [ "$DEVPANELOS" == "debian" ];then
        apt-get -y remove shellinabox
        rm -rf /etc/letsencrypt
        rm -rf /opt/letsencrypt
        rm -f $SHELLVHOST
        assign_deref_os_fs_path_ex_or_exit apachectl "$sys_dir" pathnames/sbin/apachectl
        $apachectl restart

##### INITIATE SERVICE WHEN SYSTEM STARTS

# Only run it if we can (ie. on RHEL/CentOS)
elif [ "$DEVPANELOS" == "centos" ] || [ "$DEVPANELOS" == "redhat" ];then
        yum -y remove shellinabox
        rm -rf /etc/letsencrypt
        rm -rf /opt/letsencrypt
        rm -f $SHELLVHOST

##### INITIATE SERVICE WHEN SYSTEM STARTS

else
  echo "unsupported OS"
  exit 1
fi
}

#Parse options
case  $1  in
        on)
                installshell
                ;;
        off)
                removeshell
                ;;
        *)
                usage
esac
