#!/bin/bash
error() { echo "ERROR${@+: }$@" >&2; exit 1; }
while getopts "i" OPTOPT
do
  case "$OPTOPT" in
    i) ;;
    *) exit 1;;
  esac
done
shift `expr $OPTIND - 1`
dir=`dirname "$0"`
vhost="$1"
ip="$2"
user="w_$vhost"
shift
$dir/check-vhost-name archive "$vhost" || error
[ -n "$ip" ] || error "No IP"
config_dir="/opt/webenabled/config/vhosts/$vhost"
fqdn=$vhost.`$dir/list-vhost-names-default` || error
key=/opt/webenabled/config/os/pathnames/etc/ssl/keys/$ip.$fqdn
cert=/opt/webenabled/config/os/pathnames/etc/ssl/certs/$ip.$fqdn
cacert=/opt/webenabled/config/os/pathnames/etc/ssl/certs/$ip.$fqdn.intermediate
[ -r "$key" ] || error no key
rm -f "$cert"
cat >"$cert"
[ -s "$cert" ] || error no cert
key_modulus=`openssl rsa -noout -modulus -in "$key"` || error "Invalid key"
cert_modules=`openssl x509 -noout -modulus -in "$cert"` || error "Invalid cert"
[ o"$key_modulus" = o"$cert_modules" ] || error "key/cert mismatch"
if [ -r "$cacert" ]
then
  openssl x509 -noout -modulus -in "$cacert" >/dev/null || error "Invalid CA cert"
fi
mkdir -p "$config_dir/ssl/ip"
touch "$config_dir/ssl/ip/$ip" || error
$dir/config-vhost-apache "$vhost" || exit 1
