#!/bin/bash
usage() {
  echo "Usage: `basename "$0"` <target_dir>

  Creates the directory structure for archives below the specified
  target_dir.
"

  exit 1
}

# main

[ $# -lt 1 -o -z "$1" ] && usage

in_target_dir="$1"
if [ ! -d "$in_target_dir" ]; then
  echo "Error: path '$in_target_dir' is not a directory." 1>&2
  exit 1
fi
target_dir=$(readlink -e "$in_target_dir")
if [ $? -ne 0 ]; then
  echo "Error: unable to determine full path of dir $in_target_dir" 1>&2
  exit 1
fi

self_bin=`readlink -e "$0"`
if [ $? -ne 0 -o -z "$self_bin" ]; then
  echo "Error: unable to detect self path of \$0 ($0)" 1>&2
  exit 1
fi
self_dir=${self_bin%/*}
sys_dir=${self_dir%/*}
dir_bin="$sys_dir/bin"

archive_vhosts_dir="$target_dir/vhost_archives"
if [ ! -d "$archive_vhosts_dir" ]; then
  mkdir -m 755 "$archive_vhosts_dir"
else
  chmod 755 "$archive_vhosts_dir"
fi

protected_dirs=( tmp $archive_vhosts_dir/removed_vhosts )
for d_dir in "${protected_dirs[@]}"; do
  if [ "${d_dir:0:1}" == / ]; then
    prot_dir="$d_dir"
  else
    prot_dir="$target_dir/$d_dir"
  fi

  if [ -d "$prot_dir" ]; then
    chmod 711 "$prot_dir"
  else
    mkdir -m 711 "$prot_dir"
  fi
done

exit 0
