#!/bin/bash

usage() {
  local prog=$(basename "$0")
  echo "Usage: $prog <vhost>

  Configures the S3 credentials for the specified vhost.

  Reads the S3 credentials from STDIN and writes to ~/.s3cfg.$vhost

  The STDIN input is expected to be in the following format:

default.access_key=asdadfasdf
default.secret_key=qwertyqwerty

"

  exit 1
}

# main
[ $# -eq 0 -o -z "$1" ] && usage

umask 077

vhost="$1"

self_bin=$(readlink -e "$0")
self_bin_dir=$(dirname "$self_bin")
sys_dir=$(readlink -e "$self_bin_dir/..")

"$sys_dir/libexec/check-vhost-name" archive "$vhost" || exit 1

s3cfg_file="$HOME/.s3cfg.$vhost"

# for privacy reasons it reads only from STDIN
#   (on shared servers it's a privacy leak to send the keys on command line)
"$sys_dir/bin/update-ini-file" -c "$s3cfg_file"
