#!/bin/bash
self_bin=$(readlink -e "$0")
if [ $? -ne 0 ]; then
  echo "Error: failed to determine self path" 1>&2
  exit 1
fi
dir="${self_bin%/*}"
sys_dir="${dir%/*}"
user="$1"
shift
command="$1"
shift
if [ -z "$user" ]
then
  echo "Usage: $0 username" >&2
  exit 1
fi

if ! . "$sys_dir/lib/functions"; then
  echo "Error: failed to load '$sys_dir/lib/functions'" 1>&2
  exit 1
fi

load_devpanel_config || exit $?

dbmgr_config_dir="$lamp__paths__mysql_instances_config_dir/$user"

root_client_cnf=$(readlink -m "$dbmgr_config_dir/root.client.cnf")

if [ -f "$root_client_cnf" ]; then
  su - -s /bin/bash -c "$command --defaults-file=$root_client_cnf $*" "$user"
else
  if ! password=`$dir/../config/os/pathnames/opt/dbmgr/current/bin/root-password --user="$user" 2>/dev/null`
  then
    echo "ERROR: cannot get root password for $user" >&2
    exit 1
  fi
  su - -s /bin/bash -c "$command -S mysql/mysql.sock -u root -p\"$password\" $*" "$user"
fi
