#!/bin/bash
dir=`dirname "$0"`
user="$1"
shift
command="$1"
shift
if [ -z "$user" ]
then
  echo "Usage: $0 username" >&2
  exit 1
fi

dbmgr_config_dir="$dir/../config/os/pathnames/opt/dbmgr/config/mysql/$user"

root_client_cnf=$(readlink -m "$dbmgr_config_dir/root.client.cnf")

if [ -f "$root_client_cnf" ]; then
  su - -s /bin/bash -c "$command --defaults-file=$root_client_cnf $*" "$user"
else
  if ! password=`$dir/../config/os/pathnames/opt/dbmgr/current/bin/root-password --user="$user" 2>/dev/null`
  then
    echo "ERROR: cannot get root password for $user" >&2
    exit 1
  fi
  su - -s /bin/bash -c "$command -S mysql/mysql.sock -u root -p\"$password\" $*" "$user"
fi
