#!/bin/bash

usage() {
  local self=${0%%*/}

  echo "Usage: $self <vhost>
  
  Disables SSL configuration for the specified vhost.
"
  exit 1
}

# main

[ $# -eq 0 -o -z "$1" ] && usage
vhost="$1"

self_bin=$(readlink -e "$0")
if [ $? -ne 0 ]; then
  echo "Error: unable to get self executable path." 1>&2
  exit 1
fi

sys_dir=${self_bin%/*/*}

aux_lib="$sys_dir/lib/functions"
if ! source "$aux_lib"; then
  echo "Error: unable to import functions from $aux_lib" 1>&2
  exit 1
fi
load_devpanel_config || exit $?

if ! "$sys_dir/libexec/check-vhost-name" name-only "$vhost"; then
  exit 1
fi

load_vhost_config "$vhost" || exit $?

if ! is_ssl_enabled_on_vhost "$vhost"; then
  echo "Warning: SSL is not enabled on vhost $vhost" 1>&2
  exit 0
fi

if ! save_opts_in_vhost_config "$vhost" "ssl.enabled = no"; then
  error "unable to update config file for vhost $vhost"
fi

if devpanel rewrite vhost config --vhost "$vhost"; then
  echo "Successfully disabled SSL configuration for vhost $vhost"
  exit 0
else
  echo "Warning: disabled SSL configuration, but failed to reload Apache" 1>&2
  exit 1
fi
