#!/bin/bash
usage() {
  local self=${0##*/}

  echo "Usage: $self <op>

       $self run -Y            - run distro updates now
       $self run-from-crontab  - helper to run from crontab (only runs the
                                 actual updates when it's enabled)
       $self help              - shows this help message

"
  exit 1
}

usage_run(){
  local self=${0##*/}

echo "
Executes updates provided by the Linux distribution.

Keep in mind that some programs may break due to unexpected updates or changes in the libraries
Use this at your own risk.

Usage: $self run -Y
"
  exit 1
}

# main

[ -z "$1" ] && usage
op="$1"
shift

self_bin=$(readlink -e "$0")
if [ $? -ne 0 ]; then
  echo "Error: unable to detect self path" 1>&2
  exit 1
fi
self_dir=${self_bin%/*}
sys_dir=${self_dir%/*}
lib_file="$sys_dir/lib/functions"

if ! source "$lib_file"; then
  echo "Error: unable to source file $lib_file"
  exit 1
fi
load_devpanel_config || exit $?

case  $op  in
        h|help)       
                usage
                ;;
        run)
                unset confirmed
                getopt_flags='Y'
                while getopts $getopt_flags OPTN; do
                  case $OPTN in
                    Y)
                      confirmed=1
                      ;;
                    *)
                      usage_run
                      ;;
                  esac
                done
                [ $OPTIND -gt 1 ] && shift $(( $OPTIND - 1 ))

                [ -z "$confirmed" ] && usage_run

                AUTOMATICLOGS="/var/log/automatic-updates.log"
                # Call function to detect OS 
                DEVPANELOS=$(devpanel_auto_detect_distro)
                if [ $? -ne 0 ]; then
                  exit 1
                fi

                # Add date to logfile
                echo "###############################################" >> $AUTOMATICLOGS; date +%y-%m-%d >> $AUTOMATICLOGS
                # Validation for ubuntu
                if [ "$DEVPANELOS" == "ubuntu" ];then
                        apt-get update -y >> $AUTOMATICLOGS; apt-get upgrade --assume-yes >> $AUTOMATICLOGS
                # Validation for Debian
                elif [ "$DEVPANELOS" == "debian" ];then
                        apt-get update -y >> \$AUTOMATICLOGS; apt-get upgrade --assume-yes >> $AUTOMATICLOGS
                # Validation for rhel/cenOS
                elif [ "$DEVPANELOS" == "centos" ] || [ "$DEVPANELOS" == "redhat" ];then
                        yum update -y >> $AUTOMATICLOGS
                else
                        echo "Could not detect OS"
                        exit 1
                fi
                ;;
        run-from-crontab)
                if is_distro_updates_enabled 2>/dev/null; then
                  "$self_bin" run -Y
                  exit $?
                fi

                exit 0
                ;;
        *)
                usage 
                ;;
esac
