#!/bin/bash
dir=`dirname $0`
dir_bin="$dir/../bin"
vhost="$1"
user="w_$vhost"
cmd="$2"
options="$3"

# using mode archive: it's OK to operate on a locked vhost
$dir/check-vhost-name archive "$vhost" || exit 1

su -ls /bin/bash $user -c 'cd ~/public_html/'$vhost'; '$dir_bin'/drush/drush -y en update' &> /dev/null
su -ls /bin/bash $user -c 'cd ~/public_html/'$vhost'; echo -n '$options' | '$dir_bin'/drush/drush --we-serialize '$cmd
exit 0
