#!/bin/bash
self_bin=`readlink -e "$0"`
dir=`dirname "$self_bin"`
dir_bin=`readlink -e "$dir/../bin"`
vhost="$1"
user="w_$vhost"
cmd="$2"
option="$3"
serialize="$4"

# using mode archive: it's OK to operate on a locked vhost
$dir/check-vhost-name archive "$vhost" || exit 1

su -ls /bin/bash $user -c 'cd ~/public_html/'$vhost'; '$dir_bin'/.path/drush -y en update' &> /dev/null
su -ls /bin/bash $user -c 'cd ~/public_html/'$vhost'; '$dir_bin'/.path/drush '$serialize' -y -b '$cmd' '"$option"
exit 0
