#!/bin/bash
usage() {
  echo "Usage: ${0##*/} <vhost> <archive_file>

  Generates a token to download the specified archive file from the given
  vhost.
"

  exit 1
}

get_real_url() {
  if [ -z "$1" ]; then
    echo "$FUNCNAME(): missing param" 1>&2
    return 1
  fi

  local url="$1"

  url=${url//@virtwww_base_domain@/$virtwww_base_domain}
  url=${url//@vhost@/$vhost}
  url=${url//@token_str@/$token_str}

  echo "$url"
}

# main

[ $# -lt 2 -o -z "$1" -o -z "$2" ] && usage

self_bin=`readlink -e "$0"`
if [ $? -ne 0 ]; then
  echo "Error: unable to get self path" 1>&2
  exit 1
fi

self_dir="${self_bin%/*}"
sys_dir="${self_dir%/*}"

lib_f="$sys_dir/lib/functions"
if ! source "$lib_f"; then
  echo "Error: unable to import $lib_f" 1>&2
  exit 1
fi

[ -z "$1" -o -z "$2" ] && usage

vhost="$1"
# using mode archive: it's OK to operate on a locked vhost
"$self_dir/check-vhost-name" archive "$vhost" || exit 1

archive_file_in="$2"

get_linux_username_from_vhost "$vhost" && \
user="$_dp_value"
if [ $? -ne 0 ]; then
  error "unable to get the linux username from vhost $vhost"
fi

assign_deref_os_prop_or_exit url_tmpl "$sys_dir" archive_download_url_tmpl
assign_deref_os_prop_or_exit data_dir "$sys_dir" data_dir

archives_dir=$(readlink -m "$data_dir/vhost_archives/$vhost")
archive_file=$(readlink -m "$archives_dir/$archive_file_in")

virtwww_base_domain=$(get_virtwww_base_domain) || exit 1

# check whether the specified file is inside the archives_dir
if [ "${archive_file#$archives_dir/}" == "$archive_file" ]; then
  error "archive file specified is out of dir $archives_dir"
fi

token_str='%%session_id%%' # let the token bin replace it
url=$(get_real_url "$url_tmpl")

token_bin="$sys_dir/bin/create-perl-cgi-session"

declare -a cmd_ar=( "$token_bin" -e +10m \
  -P archive_file="$archive_file" \
  -P devpanel_app=download-vhost-archive -O "$url" )

su -l -c "${cmd_ar[*]}" "$user"
