#!/bin/bash
# set -x

usage() {
  local prog=$(basename "$0")
  cat << EOF

Adds the lines to ~/public_html/.htaccess to password protect the given vhost

Usage: $prog [ options ] <vhost>

  Options:
    -b  <string>          sets the initial string delimiter
    -B  <string>          sets the ending  string delimiter
    -R  <string>          sets the realm of authentication
    -p                    read user passwords from stdin

EOF

  exit 1
}

# main()
lock_start_str='# Start of CE Password Protect'
lock_end_str='# End of CE Password Protect'
realm="CloudEnabled"

[ $# -lt 1 ] && usage

unset read_pw_stdin
getopt_flags='pb:B:R:'
while getopts $getopt_flags OPT ; do
  case "$OPT" in
    b)
      lock_start_str="$OPTARG"
      ;;
    B)
      lock_end_str="$OPTARG"
      ;;
    R)
      realm="$OPTARG"
      ;;
    p)
      read_pw_stdin=1
      ;;
    ?)
      usage
      ;;
  esac
done
[ -n "$OPTIND" -a $OPTIND -gt 1 ] && shift $(( $OPTIND - 1 ))

dir=`dirname $0`
[ "$dir" == "." ] && dir="$PWD"
dir_bin="$dir/../bin"
vhost="$1"
password="$2"
user="w_$vhost"

# using mode archive: it's OK to operate on a locked vhost
$dir/check-vhost-name archive "$vhost" || exit 1

#status=$(su -l -c '"'"$dir"'/htaccess-lock-status-vhost" "'"$vhost"'"' "$user")
status=$("$dir/htaccess-lock-status-vhost" "$vhost")
if [ "$status" == "0" ]; then
  su -l -c 'cat << EOF >> ~/public_html/.htaccess
'"$lock_start_str"'
AuthUserFile "$HOME/.htpasswd"
AuthType Basic
AuthName "'"$realm"'"
Require valid-user
Satisfy any
Order Deny,Allow
Deny from all
'"$lock_end_str"'
EOF
' "$user"
status=$?

  if [ $status -ne 0 ]; then
    echo "Error: unable to add the lines to enable password protection. cat returned $status." 1>&2
    exit $status
  fi

  su -l -c "chmod 644 ~/public_html/.htaccess" "$user";
  status=$?
  if [ $status -ne 0 ]; then
    echo "Warning: unable to set .htaccess mode to 644. chmod returned $status." 1>&2
  fi

  su -l -c '[ ! -f "~/.htpasswd" ] && touch ~/.htpasswd && chmod 640 ~/.htpasswd' "$user"
  if [ $? -ne 0 ]; then
    echo "Warning: unable to create and set permissions for .htpasswd." 1>&2
  fi

  if [ -n "$read_pw_stdin" ]; then
    su -l -c "$dir_bin/htpasswd-bulk ~/.htpasswd" "$user"
    status=$?
    if [ $status -eq 0 ]; then
      echo "Successfully password protected vhost." 1>&2
      exit 0
    else
      echo "Error: vhost protected, but unable to add users. htpasswd-bulk returned $status" 1>&2
      exit $status
    fi
  fi
else
  echo "Warning: vhost already locked." 1>&2
fi

exit 0
