#!/bin/bash
# Usage: import-vhost -s SUBSYSTEM VHOST
# Options:
#   -p do not reset web application passwords
#   -i pass mysql passwd via stdin

error()
{
  echo "ERROR${1+: }$@" >&2
  exit 1
}

subsystem=""
target_options=""

while getopts "s:np" OPTOPT
do
  case "$OPTOPT" in
    s) subsystem="$OPTARG";;
    p) target_options="$target_options${target_options+ }-p";;
    i) target_options="$target_options${target_options+ }-i";;
    *) exit 1;;
  esac
done
shift `expr $OPTIND - 1`

[ -z "$subsystem" ] && error "invalid subsystem"

dir=`dirname "$0"`
dir_bin="$dir/../bin"
vhost="$1"
user_web="w_$vhost"
vhost_config_dir=.webenabled/private
run()
{
  echo "  Running $@"
  "$@"
}
run2()
{
  echo "  Running $@" >&2
  "$@"
}
run_su()
{
  echo "  running su -l -c '$@' $user_web" >&2
  su -l -c "$*" "$user_web"
}

$dir/check-vhost-name restore "$vhost" || error
home="`eval \"echo ~$user_web\"`" || error

config="`sed \"\\$a\
subsystem=\$subsystem\"`"

if ! TMPFILE="`mktemp -t import_vhost.XXXXXXXXXX`"
then
  echo "ERROR: mktemp failed";
  exit 1
fi

trap 'echo "Removing temporary archive $TMPFILE"; rm -f -- "$TMPFILE"' \
  EXIT HUP INT QUIT ILL TRAP ABRT BUS FPE KILL SEGV PIPE STOP ALRM TERM


echo "Export stage 1: transferring archive from external hosting"
config_size=`echo "$config" | wc -l` || error
(echo "Lines: $config_size"; echo "$config"; echo end) | su -lc 'bin/hosting_link import' 'export' >"$TMPFILE" || error


echo "Export stage 2: restore $vhost from $TMPFILE"
if ! $dir/restore-vhost $target_options "$vhost" - <"$TMPFILE"
then
  echo ERROR >&2
  exit 1
fi

echo "Export stage 3: final configuration"

run_su WEBENABLED_HOSTING_LINK_BASE_URL=none $dir_bin/restore-vhost-subsystem -n -s "$subsystem" || exit 1

#rewrite_base_sed_script=":a
#s|^[[:space:]]*RewriteBase[[:space:]]*.*|RewriteBase $WEBENABLED_HOSTING_LINK_REWRITE_BASE|
#tb
#\$a\\
#RewriteBase $WEBENABLED_HOSTING_LINK_REWRITE_BASE
#n
#ba
#:b
#{
#n
#bb
#}
#"
#
#if [ -n "$WEBENABLED_HOSTING_LINK_REWRITE_BASE" ]
#then
#    echo "$rewrite_base_sed_script" | run_su "$dir_bin/ised" -p -I -L -f - -- "public_html/$vhost/.htaccess" || exit 1
#fi
