#!/bin/bash

self_bin=$(readlink -e "$0")
if [ $? -ne 0 ]; then
  echo "Error: unable to detect self path" 1>&2
  exit 1
fi
self_dir=${self_bin%/*}
sys_dir=${self_dir%/*}

for file in "$sys_dir/install/utils/interfaces-pre-up/"*; do
  if [ -f "$file" -a -x "$file" ]; then
    "$file" "$@" || true
  fi
done
