#!/bin/bash
usage() {
  local prog=$(basename "$0")
  echo "Usage: $prog <vhost> <password>

  This script updates the password of the vhost user on mysql (w_vhost)
  and updates the relevant files on the vhost home directory. It also
  updates the app configuration files to apply the new password.
"
  exit 1
}

# main

[ $# -lt 2 -o -z "$1" -o -z "$2" ] && usage

self_bin=$(readlink -e "$0")
dir=$(dirname "$self_bin")
sys_dir=$(readlink -e "$dir/..")
dir_bin="$sys_dir/bin"

vhost="$1"
password="$2"

user="w_$vhost"
db_user="b_$vhost"
user_home=$(eval echo \~"$user")

# using mode archive: it's OK to operate on a locked vhost
"$dir/check-vhost-name" archive "$vhost" || exit 1

lib_file="$sys_dir/lib/functions"
if ! source "$lib_file"; then
  echo "Error: unable to load file $lib_file" 1>&2
  exit 1
fi

if [ -d /opt/dbmgr ]; then
  dbmgr_dir="/opt/dbmgr" # backwards compatibility with old WE VPSs
elif [ -d "$sys_dir/compat/dbmgr" ]; then
  dbmgr_dir="$sys_dir/compat/dbmgr"
else
  error "unable to find dbmgr directory"
fi

"$dbmgr_dir/current/bin/user-password" --user="$db_user" --db-user="$user" --db-password="$password"
dbmgr_status=$?
if [ $dbmgr_status -ne 0 ]; then
  echo "Error: unable to change user mysql instance password. dbmgr returned status: $dbmgr_status"
  exit 1
fi

printf "set app:0:_:db_password $password\n" | 
  "$sys_dir/libexec/apache-metadata-handler" "$vhost"
if [ $? -ne 0 ]; then
  echo "Warning: unable to update apache metadata." 1>&2
fi

# change phpmyadmin password
htpasswd_file="$user_home/.webenabled/private/.htpasswd.phpmyadmin"

su -l -c "cat << EOF | $dir_bin/htpasswd-bulk $htpasswd_file
~:$user:$password
EOF
" "$user"

ht_status=$?
if [ $ht_status -ne 0 ]; then
  echo "Warning: changing htpasswd password for user '$user'. htpasswd-bulk returned status code: $ht_status" 1>&2
fi

mysql_passwd_file="$user_home/.webenabled/private/.mysql.passwd"

if [ -f "$user_home/.my.cnf" ]; then
  echo "client.password=$password" | su -l -c "$dir_bin/update-ini-file"' '"$user_home/.my.cnf"  "$user"
  if [ $? -ne 0 ]; then
    echo "Warning: filed to update ~/.my.cnf file" 1>&2
  fi
fi

if [ -f "$mysql_passwd_file" ]; then
  password_esc=$(escape_sed "$password")
  su -l -c 'sed -i -e "s/^'"$user"':.*/'"$user:$password_esc"'/" '"$mysql_passwd_file" "$user"
  if [ $? -ne 0 ]; then
    echo "Warning: failed to update mysql passwd file $mysql_passwd_file" 1>&2
  fi
fi

su -l -c "$dir_bin/restore-vhost-subsystem"' '-n "$user"
if [ $? -ne 0 ]; then
  echo "Warning: file to update application files" 1>&2
fi

exit 0
