#!/bin/bash
# set -x 
dir=`dirname $0`
[ $dir == "." ] && dir="$PWD"
dir_bin="$dir/../bin"
vhost="$1"
user="w_$vhost"
db_user="b_$vhost"
password="$2"
user_home=$(eval echo ~"$user")

usage() {
  local prog=$(basename "$0")
  printf "Usage:\n  %s <vhost> <password>\n" "$prog"
  exit 1
}

escape_sed() {
  local pass="$1"
  pass=${pass//\\/\\\\}
  pass=${pass//\//\\/}
  pass=${pass//\;/\\\;}
  pass=${pass//\*/\\*}

  echo -n $pass
}

[ $# -lt 2 ] && usage


# using mode archive: it's OK to operate on a locked vhost
$dir/check-vhost-name archive "$vhost" || exit 1

/opt/dbmgr/current/bin/user-password --user="$db_user" --db-user="$user" --db-password="$password"
dbmgr_status=$?
if [ $dbmgr_status -ne 0 ]; then
  echo "Error: unable to change user mysql instance password. dbmgr returned status: $dbmgr_status"
  exit 1
fi

#set -x
# change phpmyadmin password
htpasswd_file="$user_home/.webenabled/private/.htpasswd.phpmyadmin"

su -l -c "cat << EOF | $dir_bin/htpasswd-bulk $htpasswd_file
=:$user:$password
EOF
" "$user"

ht_status=$?
if [ $ht_status -ne 0 ]; then
  echo "Error changing htpasswd password for user '$user'. htpasswd-bulk returned status code: $ht_status"
  exit $ht_status
fi

mysql_passwd_file="$user_home/.webenabled/private/.mysql.passwd"

password=$(escape_sed "$password" )
if [ -f "$user_home/.my.cnf" ]; then
 su -l -c 'sed -i -e "s/^password=.*/password='"$password"'/" '"$user_home/.my.cnf" "$user"
fi

if [ -f "$mysql_passwd_file" ]; then
  su -l -c 'sed -i -e "s/^'"$user"':.*/'"$user:$password"'/" '"$mysql_passwd_file" "$user"
fi
