#!/bin/bash
usage() {
  echo "Usage: `basename "$0"` <vhost>"
  exit 1
}

# main

[ $# -lt 1 ] && usage

self_bin=`readlink -e "$0"`
dir=`dirname "$self_bin"`
dir_bin="$dir/../bin"
vhost="$1"
user="w_$vhost"

# using mode archive: it's OK to operate on a locked vhost
"$dir/check-vhost-name" archive "$vhost" || exit 1

token_bin="$dir/token-mgr"

if [ -x "$token_bin" ]; then
  "$token_bin" -p -t phpmyadmin "$vhost"
  status=$?
else
  grep -E '^[[:space:]]*Use' "$dir"/../../compat/apache_include/virtwww/${user}.conf | sed 's,^.\+ \([^[:space:]]\+\)$,\1,g'
  status=$?
fi

exit $status
