#!/bin/bash
usage() {
  echo "Usage: `basename "$0"` <vhost>"
  exit 1
}

# main

[ $# -lt 1 ] && usage

self_bin=`readlink -e "$0"`
dir=${self_bin%/*}
sys_dir=${dir%/*}
dir_bin="$sys_dir/bin"

vhost="$1"
$sys_dir/libexec/check-vhost-name archive "$vhost" || exit 1

lib_f="$dir/../lib/functions"
if ! source "$lib_f"; then
  echo "Error: unable to import $lib_f" 1>&2
  exit 1
fi

get_linux_username_from_vhost "$vhost" && \
user="$_dp_value"
if [ $? -ne 0 ]; then
  error "unable to get the linux username from vhost $vhost"
fi

token_bin="$dir/token-mgr"

if [ -x "$token_bin" ]; then
  "$token_bin" -p -t phpmyadmin "$vhost"
  status=$?
else
  grep -E '^[[:space:]]*Use' "$dir"/../../compat/apache_include/virtwww/${user}.conf | sed 's,^.\+ \([^[:space:]]\+\)$,\1,g'
  status=$?
fi

exit $status
