#!/bin/bash
usage() {
  echo "Usage: `basename "$0"` <vhost>"
  exit 1
}

# main

[ $# -lt 1 ] && usage

self_bin=`readlink -e "$0"`
dir=${self_bin%/*}
sys_dir=${dir%/*}
dir_bin="$sys_dir/bin"

vhost="$1"
$sys_dir/libexec/check-vhost-name archive "$vhost" || exit 1

lib_f="$dir/../lib/functions"
if ! source "$lib_f"; then
  echo "Error: unable to import $lib_f" 1>&2
  exit 1
fi
load_devpanel_config || exit $?

load_vhost_config "$vhost" || exit $?
user="$v__vhost__linux_user"
token_bin="$dir/token-mgr"

if [ -x "$token_bin" ]; then
  "$token_bin" -p -t phpmyadmin "$vhost"
  status=$?
else
  grep -E '^[[:space:]]*Use' "$dir"/../../compat/apache_include/virtwww/${user}.conf | sed 's,^.\+ \([^[:space:]]\+\)$,\1,g'
  status=$?
fi

exit $status
