#!/bin/bash
error()
{
  echo "ERROR${@+: }$@" >&2
  exit 1
}
identity_dir=/opt/webenabled/config/ssh/tmp
weadmin_group=weadmin

read -r key || error "no key"
id=`echo "$key"|sed -n 's/.* webenabled one-time key id=\([-_.A-Za-z0-9]\{1,\}\)$/\1/p'` || error
[ -n "$id" ] || error "invalid key id"
identity_subdir="$identity_dir/$id"
identity="$identity_subdir/id_rsa"
[ -d "$identity_subdir" ] || error "key not found (1)"
[ -r "$identity" ] || error "key not found (2)"
[ -r "$identity.pub" ] || error "key not found (3)"
fgrep -q -x "$key" "$identity.pub" || error "key mismatch"
rm -rf "$identity_subdir"
