#!/bin/bash
usage() {
  echo "Usage: ${0##*/} <vhost> <archive_file>

  Removes the specified archive file from the given vhost.
"

  exit 1
}

# main

[ $# -lt 2 -o -z "$1" -o -z "$2" ] && usage

self_bin=`readlink -e "$0"`
if [ $? -ne 0 ]; then
  echo "Error: unable to get self path" 1>&2
  exit 1
fi

self_dir="${self_bin%/*}"
sys_dir="${self_dir%/*}"

lib_f="$sys_dir/lib/functions"
if ! source "$lib_f"; then
  echo "Error: unable to import $lib_f" 1>&2
  exit 1
fi

[ -z "$1" -o -z "$2" ] && usage

vhost="$1"
archive_file_in="$2"

user="w_$vhost"

assign_deref_os_prop_or_exit data_dir "$sys_dir" data_dir

# using mode archive: it's OK to operate on a locked vhost
"$self_dir/check-vhost-name" archive "$vhost" || exit 1

archives_dir=$(readlink -m "$data_dir/vhost_archives/$vhost")
archive_file=$(readlink -m "$archives_dir/$archive_file_in")

virtwww_base_domain=$(get_server_base_domain) || exit 1

# check whether the specified file is inside the archives_dir
if [ "${archive_file#$archives_dir/}" == "$archive_file" ]; then
  error "archive file specified is out of dir $archives_dir"
fi

if [ -f "$archive_file" ]; then
  rm -v -f "$archive_file"
else
  echo "Warning: file '$archive_file' does not exist." 1>&2
fi

exit 0
