#!/bin/sh
dir=`dirname "$0"`
error()
{
  echo "ERROR${1+: }$@" >&2
  exit 1
}

[ $# = 1 ] || error "One argument required"
user="$1"
id "$user" >/dev/null || error "No such user"

signal=TERM
for i in 1 2 3 4 5 6
do
  [ $i = 4 ] && signal=KILL
  output=`ps --no-headers -U "$user"|awk '{print $1}'|tr '\n' ' '`
  if [ -n "$output" ]
  then
    echo "Killing $user's mysqld processes with SIG$signal"
    echo "$output"
    su -l -s /bin/bash -c "kill -$signal $output" "$user"
    sleep 5
  else
    break
  fi
done


echo "Checking whether there are still processes run by $user"
output="`ps --no-headers -U \"$user\"`"

if [ -n "$output" ]
then
  echo "$output"|sed 's/^/  /'
  error "not all processes are dead, aborting"
fi

echo "Removing the user $user"
userdel -r "$user"
case $? in
  0) ;;
  8) # Logged in
     echo "User still logged in, trying to fix utmp"
     "$dir/remove-user-utmp" || echo "Warning: failed to fix utmp"
     userdel -r "$user" || error "userdel failed"
     ;;
  *) error
     ;;
esac
