#!/bin/bash

usage() {
  echo "Usage: `basename "$0"` <template_file> <target_file> <key1=value1> [ key2=value2 ]"
  exit 1
}

# main
[ $# -lt 3 ] && usage

self_bin=`readlink -e "$0"`
curr_dir=`dirname "$self_bin"`
we_base_dir=`readlink -e "$curr_dir/.."`

lib_file="$we_base_dir/lib/functions"
if ! source "$lib_file"; then
  echo "Error: unable to source file '$lib_file'" 1>&2
  exit 1
fi

template_file="$1"
target_file="$2"
shift 2

sed_tmp_file=`mktemp`
trap 'rm -f -- "$sed_tmp_file"' EXIT

while [ -n "$1" ]; do
  pair="$1"
  key=${pair%%=*}
  value=${pair#*=}

  key_escaped=`escape_sed "$key"`
  value_escaped=`escape_sed "$value"`

  echo "s/@@__${key_escaped}__@@/$value_escaped/g;" >> "$sed_tmp_file"
  shift
done

cp -f "$template_file" "$target_file"

sed -i -f "$sed_tmp_file" "$target_file"
