#!/bin/bash

# This script is just for backwards compatibility with Webenabled
# newer software should use ../bin/run-vhost-shell

usage() {
  echo "Usage: $(basename $0) <vhost> <command>"
  exit 1
}

[ $# -lt 2 -o -z "$1" -o -z "$2" ] && usage

#

vhost="$1"
command="$2"

user="w_$vhost"
if ! getent passwd "$user" &>/dev/null; then
  echo "Error: unknown user" 1>&2
  exit 1
fi

su -l -c "$command" "$user"
