#!/bin/bash

# This script is just for backwards compatibility with Webenabled
# newer software should use ../bin/run-vhost-shell

usage() {
  echo "Usage: $(basename $0) <vhost> <command>"
  exit 1
}

[ $# -lt 2 -o -z "$1" -o -z "$2" ] && usage

# main
self_bin=`readlink -e "$0"`
if [ $? -ne 0 ]; then
  echo "Error: unable to get self path" 1>&2
  exit 1
fi

self_dir="${self_bin%/*}"
sys_dir="${self_dir%/*}"

lib_f="$sys_dir/lib/functions"
if ! source "$lib_f"; then
  echo "Error: unable to import $lib_f" 1>&2
  exit 1
fi

vhost="$1"
$sys_dir/libexec/check-vhost-name archive "$vhost" || exit 1

get_linux_username_from_vhost "$vhost" && \
user="$_dp_value"
if [ $? -ne 0 ]; then
  error "unable to get the linux username from vhost $vhost"
fi

command="$2"

if ! getent passwd "$user" &>/dev/null; then
  echo "Error: unknown user" 1>&2
  exit 1
fi

su -l -c "$command" "$user"
