#!/bin/bash
usage() {
  local prog=$(basename "$0")
  echo "Usage: $prog Yes"
  exit 1
}

[ $# -ne 1 -o "$1" != "Yes" ] && usage

( 
  sleep 5 # sleep some seconds to give time for taskd 
          # to report the exit status

  shutdown -r now
) &

exit 0
