#!/bin/bash

declare php_series_regex='^[0-9]\.[0-9]$'
declare php_version_regex='^[0-9]\.[0-9]\.[0-9][0-9]?$'

usage() {
  echo "Usage: ${0##*/} set   <vhost> <version>
Usage: ${0##*/} unset <vhost> 

Sets or unsets a specific PHP version for the specified vhost.

Both the series (e.g. 5.3, 5.6, etc) or a specific version (e.g. 5.3.10) can
be specified when setting. But preferrably specify the series as it's less
prone to errors after updates.

Examples:
  
  Set version 5.3 for vhost "asdf":
    # ${0##*/} set asdf 5.3

  Remove previously defined version for vhost "asdf":
    # ${0##*/} unset asdf

"
  exit 1
}

# main

[ $# -lt 2 -o -z "$1" -o -z "$2" ] && usage

unset is_series is_version_specific

self_bin=$(readlink -e "$0")
if [ $? -ne 0 ]; then
  echo "Error: unable to detect self path" 1>&2
  exit 1
fi

self_dir=${self_bin%/*}
sys_dir=${self_dir%/*}
lib_file="$sys_dir/lib/functions"

if ! source "$lib_file"; then
  echo "Error: unable to source lib file '$lib_file'" 1>&2
  exit 1
fi

op="$1"
if [ "$op" != "set" -a "$op" != "unset" -a "$op" != "get" ]; then
  error "invalid operation specified."
elif [ "$op" == set -a -z "$3" ]; then
  error "missing version parameter"
fi

vhost="$2"
recvd_version="$3"

if ! "$self_dir/check-vhost-name" archive "$vhost"; then
  exit 1
fi

if [ "$op" == set ]; then
  if [[ "$recvd_version" =~ $php_series_regex ]]; then
    series=$recvd_version
    version=$(get_php_version_for_series "$recvd_version")
    if [ $? -ne 0 ]; then
      error "unable to find installed version for series $recvd_version"
    fi
    version_txt="$series"
    is_series=1
  elif [[ "$recvd_version" =~ $php_version_regex ]]; then
    version="$recvd_version"
    version_txt="$version"
    series=${version%.*}
    is_version_specific=1
  else
    error "invalid format for the version specified"
  fi

  if ! get_php_bin_for_version "$version" >/dev/null; then
    error "unable to find PHP binary for version $version ${is_series:+(series $series)}"
  fi

  echo "set app:0:_:php_version $version_txt" | \
    "$self_dir/apache-metadata-handler" -q "$vhost"
  if [ $? -eq 0 ]; then
    if [ -n "$is_version_specific" ]; then
      echo "Successfully set PHP version to $version on vhost $vhost."
    elif [ -n "$is_series" ]; then
      echo "Successfully set PHP to series $series on vhost $vhost."
    fi
  else
    error "unable to set PHP version to $version on vhost $vhost."
  fi
elif [ "$op" == unset ]; then
  echo "rm app:0:_:php_version" | \
    "$self_dir/apache-metadata-handler" -q "$vhost"
  if [ $? -eq 0 ]; then
    echo "Successfully unset PHP version from vhost $vhost."
  else
    error "unable to unset PHP version on vhost $vhost."
  fi
elif [ "$op" == get ]; then
  version=$(get_php_version_for_vhost "$vhost")
  if [ -n "$version" ]; then
    echo "$version"
  else
    echo "No PHP version defined for vhost $vhost." 1>&2
  fi
fi

exit 0
