#!/bin/sh
dir=`dirname $0`
dir_bin="$dir/../bin"
vhost="$1"
url="$2"
path="$3"
username="$4"
password="$5"
user="w_$vhost"

# using mode archive: it's OK to operate on a locked vhost
$dir/check-vhost-name archive "$vhost" || exit 1

# Checkout the current working copy
rm -rf ~/.subversion
mkdir /home/clients/websites/${user}/.svn-cwco
cd  /home/clients/websites/${user}/.svn-cwco
svn co http://${url}/${path} --username $username --password $password -q --non-interactive -N

# Copy the .svn and .subversion folder over to the vhost root
if [ $? -eq 0 ]; then
    chown -R ${user}:virtwww $(basename $path)
    cp -a $(basename $path)/.svn ../public_html/${vhost}/
    cd ..
    rm -rf .svn-cwco

    chown -R ${user}:virtwww ~/.subversion
    rm -rf ~/.subversion
    #cp -a ~/.subversion /home/clients/websites/$user/
else
    echo svn connection failed
    exit 1
fi
