#!/bin/bash

usage() {
  echo "Usage: `basename "$0" [git_ref]`
  
  This script updates the DevPanel scripts to the latest version if none is
  specified, or updates to the specified git ref.
"
  exit 1
}

# main
[ "$1" == "-h" ] && usage

self_bin=$(readlink -e "${BASH_SOURCE[0]}")
if [ $? -ne 0 ]; then
  echo "Error: unable to get self path" 1>&2
  exit 1
fi
self_dir=${self_bin%/*}
sys_dir=${self_dir%/*}
lib_file="$sys_dir/lib/functions"

#
# change the default umask so that files don't get too restriced
# permissions on systems with a more restrictive umask
#
umask 022

if ! source "$lib_file"; then
  echo "Error: unable to source file '$lib_file'" 1>&2
  exit 1
fi

ref="${1:-master}"

GIT_DIR="$sys_dir/.git"
GIT_WORK_TREE="$sys_dir"
export GIT_DIR GIT_WORK_TREE

if [ ! -d "$GIT_DIR" ]; then
  echo "Error: path '$GIT_DIR' is not a directory. Can't update."
  exit 1
fi

if ! git fetch; then
  error "unable to fetch updates from git"
fi

if ! git fetch --tags; then
  error "unable to fetch tags from git"
fi

if ! git checkout -f "$ref"; then
  error "unable to switch/cleanup local code to ref '$ref'"
fi

if ! git pull --rebase origin "$ref"; then
  error "unable to merge changes from origin/$ref"
fi

echo "Successfully updated script files"
