#!/bin/bash

usage() {
  echo "Usage: `basename "$0" [ version_str ]`
  
  This script updates the DevPanel scripts to the latest version if none is
  specified, or updates to the specified version.
"
  exit 1
}

curr_dir=`dirname "${BASH_SOURCE[0]}"`
lib_file="$curr_dir/../lib/functions"

# main

[ "$1" == "-h" ] && usage

if ! source "$lib_file"; then
  echo "Error: unable to source file '$lib_file'" 1>&2
  exit 1
fi

ref="${1:-master}"

cd "$curr_dir/../"

if ! git fetch; then
  error "unable to fetch updates from git"
fi

if ! git fetch --tags; then
  error "unable to fetch tags from git"
fi

if ! git checkout "$ref"; then
  error "unable to checkout version $ref from git"
fi

echo "Successfully updated script files"
