#!/bin/bash

new_hostname="$1"
old_hostname="$2"

if [ -z "$new_hostname" ]; then
  echo "Error: missing new hostname" 1>&2
  exit 1
fi

self_bin=`readlink -e "$0"`
dir_bin=`dirname "$self_bin"`
system_dir=`readlink -e "$dir_bin/../../.."`

apache_include_dir="$system_dir/compat/apache_include"
git_vhost_file="$apache_include_dir/virtwww/default_git_vhost.conf"
if [ ! -f "$git_vhost_file" ]; then
  exit 0 # file missing, no update needed
fi

lib_file="$system_dir/lib/functions"
if ! source "$lib_file"; then
  echo "Error: unable to source lib file '$lib_file'"
  exit 1
fi

assign_deref_os_prop_or_exit git_vhost_template "$system_dir" \
  names/git_vhost_template

"$system_dir/bin/template-tool" -o "$git_vhost_file" \
  "$apache_include_dir/$git_vhost_template" apache_virtwww_domain

if [ $? -ne 0 ]; then
  error "unable to update the server domain."
fi

hash -p "$system_dir/config/os/pathnames/sbin/apachectl" apachectl
if apachectl configtest; then
  apachectl graceful
else
  error "invalid apache configuration!!! This is an unknown error. You need to open a support ticket"
fi
