#!/bin/bash

new_hostname="$1"
old_hostname="$2"

if [ -z "$new_hostname" ]; then
  echo "Error: missing new hostname" 1>&2
  exit 1
fi

self_bin=`readlink -e "$0"`
dir_bin=${self_bin%/*}
system_dir=${dir_bin%/*/*/*}

apache_include_dir="$system_dir/compat/apache_include"
git_vhost_file="$apache_include_dir/global-includes/cgit.conf"
if [ ! -f "$git_vhost_file" ]; then
  exit 0 # file missing, no update needed
fi

lib_file="$system_dir/lib/functions"
if ! source "$lib_file"; then
  echo "Error: unable to source lib file '$lib_file'"
  exit 1
fi

git_vhost_template=$(get_git_vhost_template ) || exit $?

"$system_dir/bin/template-tool" -o "$git_vhost_file" \
  "$apache_include_dir/$git_vhost_template" apache_virtwww_domain

if [ $? -ne 0 ]; then
  error "unable to update the server domain."
fi

if apache_configtest; then
  reload_or_start_apache
else
  error "invalid apache configuration!!! This is an unknown error. You need to open a support ticket"
fi
