#!/bin/sh
# $Owl: Owl/packages/openssh/sftp.control,v 1.3 2005/11/16 13:21:53 solar Exp $

. /etc/control.d/functions

CONFIG=/etc/ssh/sshd_config

new_subst on \
	'^Subsystem[[:space:]]+sftp[[:space:]]+/usr/libexec/ssh/sftp-server$' \
	's,^#*\(Subsystem[[:space:]]\+sftp[[:space:]]\+\)\(/usr/libexec/ssh/sftp-server\|/usr/local/libexec/sftp-server-wrapper\),\1/usr/libexec/ssh/sftp-server,'
new_subst off \
	'^#Subsystem[[:space:]]+sftp[[:space:]]+/usr/libexec/ssh/sftp-server$' \
	's,^\(Subsystem[[:space:]]\+sftp[[:space:]]\+\)\(/usr/libexec/ssh/sftp-server\|/usr/local/libexec/sftp-server-wrapper\),#\1/usr/libexec/ssh/sftp-server,'
new_subst wrapper \
	'^Subsystem[[:space:]]+sftp[[:space:]]+/usr/local/libexec/sftp-server-wrapper$' \
	's,^#*\(Subsystem[[:space:]]\+sftp[[:space:]]\+\)\(/usr/libexec/ssh/sftp-server\|/usr/local/libexec/sftp-server-wrapper\),\1/usr/local/libexec/sftp-server-wrapper,'

# Backwards compatibility
test "$*" = enabled && set - on
test "$*" = disabled && set - off

control_subst "$CONFIG" "$*" || exit 1

case "$*" in
on|off|wrapper)
	/etc/rc.d/init.d/sshd reload
	;;
esac
