#!/bin/bash
#

for instance in $(get_list_of_mysql_instances); do
  unset vhost

  load_mysql_instance_config "$instance" || continue

  args_ar=(  "params.shared = no" )
  args_ar+=( "params.host_type = $mysql__params__type" )
  args_ar+=( "- params.type" )

  if [[ "$instance" == b_* ]]; then
    w_user="w_${instance#b_}"

    if vhost=$(get_vhost_from_linuxuser "$w_user" ); then
      :
    fi
  elif vhost_exists "$instance" ; then
    vhost="$instance"
  fi

  if [ -n "$vhost" ] && load_vhost_config "$vhost"; then
    if is_vhost_enabled "$vhost"; then
      args_ar+=( "params.enabled = yes" )
      args_ar+=( "params.vhosts +=w $vhost" )
    fi
  else
    args_ar+=( "params.enabled = yes" )
  fi

  save_opts_in_mysql_instance "$instance" "${args_ar[@]}"
done
