#!/bin/bash -e

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

ZabbixHostname=$2

usage(){
local self=${0##*/}
echo -ne "This script is used to install zabbix client so it can communicate with devpanel monitoring
Usage:
      $self <on|off>

"
}

# Call functions script to import detect_os method
self_bin=$(readlink -e "$0")
self_dir=${self_bin%/*}
sys_dir=${self_dir%/*}
lib_file="$sys_dir/lib/functions"

if ! source "$lib_file"; then
  echo "Error: unable to source file $lib_file"
  exit 1
fi

patch_zabbix_config()
{
  local sed_str=""
  sed_str="\
    s/Server=127.0.0.1/Server=monitoring.devpanel.com/;
    s/ServerActive=127.0.0.1/ServerActive=monitoring.devpanel.com/;
    s/Hostname=Zabbix\ server/Hostname=$ZabbixHostname/;
    s/# EnableRemoteCommands=0/EnableRemoteCommands=1/;"
  sed -i "$sed_str" /etc/zabbix/zabbix_agentd.conf
}

patch_sudoers()
{
  # avoid duplicates
  if [ ! `grep -Fxq "zabbix ALL=NOPASSWD" /etc/sudoers` ]; then sed -i 's/^zabbix\ ALL=NOPASSWD.*//g' /etc/sudoers; fi
  echo "zabbix ALL=NOPASSWD: /opt/webenabled/sbin/check_mem_diskspace_usage.sh" >> /etc/sudoers
  echo "zabbix ALL=NOPASSWD: /opt/webenabled/sbin/check_apache2_logs.sh" >> /etc/sudoers
  echo "zabbix ALL=NOPASSWD: /opt/webenabled/sbin/check_git_update.sh" >> /etc/sudoers
}

installzabbix(){
DEVPANELOS=$(devpanel_auto_detect_distro)

# Only run it if we can (ie. on Ubuntu/Debian)
if [ "$DEVPANELOS" == "ubuntu" ] || [ "$DEVPANELOS" == "debian" ];then
  apt-get update
  apt-get -y install zabbix-agent sysv-rc-conf
  sysv-rc-conf zabbix-agent on
  patch_zabbix_config
  patch_sudoers
  service zabbix-agent restart

# Only run it if we can (ie. on RHEL/CentOS)
elif [ "$DEVPANELOS" == "centos" ] || [ "$DEVPANELOS" == "redhat" ];then
  yum -y update
  rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm
  yum -y install zabbix-agent
  chkconfig zabbix-agent on
  patch_zabbix_config
  patch_sudoers
  service zabbix-agent restart

else
  echo "unsupported OS"
  exit 1
fi
}

removezabbix(){
DEVPANELOS=$(devpanel_auto_detect_distro)
# Only run it if we can (ie. on Ubuntu/Debian)
if [ "$DEVPANELOS" == "ubuntu" ] || [ "$DEVPANELOS" == "debian" ];then
  apt-get -y remove zabbix-agent 

# Only run it if we can (ie. on RHEL/CentOS)
elif [ "$DEVPANELOS" == "centos" ] || [ "$DEVPANELOS" == "redhat" ];then
  yum -y remove zabbix-agent zabbix zabbix-release

else
  echo "unsupported OS"
  exit 1
fi
}

#Parse options
case  $1  in
        on)       
                installzabbix
                ;;
        off)
                removezabbix
                ;;            
        *)
                usage              
esac
