FROM devpanel_cache:v3
EXPOSE 4000

ARG USER=$USER
ARG APP=$APP
ARG SEEDAPP_ARCHIVE=$SEEDAPP_ARCHIVE
ARG DOMAIN=$DOMAIN

# get seedapp
#RUN mkdir /opt/webenabled/${APP} && cd /opt/webenabled/${APP} && wget https://www.webenabled.com/seedapps/${SEEDAPP_ARCHIVE} && tar zxvf ${SEEDAPP_ARCHIVE}

# setup environment for the app
RUN /opt/webenabled/libexec/config-vhost-names-default ${DOMAIN}
RUN /opt/webenabled/libexec/restore-vhost -F ${USER} /opt/webenabled/${APP}
RUN mv /etc/mysql/my.cnf /etc/mysql/my.cnf.orig

# start services
## create script with variables before CMD, since after it will not be parsed
ADD ./mysql_start.sh /tmp/mysql_start.sh
## run mysql
CMD bash /tmp/mysql_start.sh
