FROM devpanel_cache:latest
EXPOSE 80

ARG USER=$USER
ARG APP=$APP
ARG SEEDAPP_ARCHIVE=$SEEDAPP_ARCHIVE
ARG DOMAIN=$DOMAIN

# setup environment for the app
COPY ${APP}_export_for_convert_ops.tgz /opt/webenabled-data/vhost_archives/
RUN /opt/webenabled/libexec/config-vhost-names-default ${DOMAIN}
RUN /opt/webenabled/libexec/restore-vhost -p ${USER} /opt/webenabled-data/vhost_archives/${APP}_export_for_convert_ops.tgz
RUN mv /etc/mysql/my.cnf /etc/mysql/my.cnf.orig

# start services
ADD ./startup.sh /tmp/startup.sh
CMD bash /tmp/startup.sh
