#!/bin/bash
dir=`dirname $0`
error()
{
  echo "ERROR${*+: }$*" >&2
  exit 1
}
if ! id we_ssh >/dev/null 2>&1
then
  useradd -m we_ssh || error
fi

su -lc "$dir/shellinaboxd -b -p 2222" we_ssh || error
