#!/bin/bash
self_bin=`readlink -e "$0"`
if [ $? -ne 0 ]; then
  echo "Error: unable to get self path" 1>&2
  exit 1
fi

self_dir="${self_bin%/*}"
sys_dir="${self_dir%/*/*}"

lib_f="$sys_dir/lib/functions"
if ! source "$lib_f"; then
  echo "Error: unable to import $lib_f" 1>&2
  exit 1
fi
load_devpanel_config || exit $?

vhost="$1"
cp_src="$2"
cp_dest="$3"
param="$4"

load_vhost_config "$vhost" || exit $?
user="$v__vhost__linux_user"

su -c "cd ~$user ; cp $param $cp_src $cp_dest" "$user"
