#!/bin/bash
error()
{
  echo "ERROR${@+: }$@" >&2
  exit 1
}
identity_dir=/opt/webenabled/config/ssh/tmp
authorized_keys=~r_we/.ssh/authorized_keys
weadmin_group=weadmin
tmp=`mktemp "$authorized_keys.XXXXXX"` || exit 1
trap 'rm -f "$tmp"' HUP INT QUIT ILL TRAP ABRT BUS FPE KILL SEGV PIPE STOP ALRM TERM
if [ -r "$authorized_keys" ]; then
  chmod --reference="$authorized_keys" "$tmp" || exit 1
  cat "$authorized_keys" >>"$tmp" || exit 1; 
fi
read -r key || error "no key"
id=`echo "$key"|sed -n 's/.* webenabled .*id=\([-_.A-Za-z0-9]\{1,\}\)$/\1/p'` || error
[ -n "$id" ] || error "invalid key id"
#echo -n 'from="127.0.0.1",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ' >>"$tmp" || exit 1
echo "$key" >>"$tmp" || exit 1
mv "$tmp" "$authorized_keys" || exit 1
