#!/bin/bash
dir=`dirname $0`
sys_dir=${dir%/*/*}
dir_bin="$sys_dir/bin"
vhost="$1"
lines="$2"

# using mode archive: it's OK to operate on a locked vhost
$sys_dir/libexec/check-vhost-name archive "$vhost" || exit 1

[ -z "$lines" ] && lines=10

lib_f="$sys_dir/lib/functions"
if ! source "$lib_f"; then
  echo "Error: unable to import $lib_f" 1>&2
  exit 1
fi
load_devpanel_config || exit $?

load_vhost_config "$vhost" || exit $?
user="$v__vhost__linux_user"

echo ' 'ACCESS
su -ls /bin/bash $user -c 'tail -n '$lines' ~/logs/'${vhost}'-access_log'
echo ' 'ERROR
su -ls /bin/bash $user -c 'tail -n '$lines' ~/logs/'${vhost}'-error_log'
echo ' 'PHP
su -ls /bin/bash $user -c 'tail -n '$((lines * 25))' ~/logs/'${vhost}'-error_log | grep '\''] PHP'\'
exit 0
